### ISSUE TITLE
getAccountInfo() raises NullPointerException on Bitstamp

### ISSUE THREAD

**Issue by iwuvjhdva** [timmolter/XChange#1074]
Hi,

I get the following error when trying to fetch balances on Bitstamp.

The code works fine with other exchanges.

Any ideas?

Thank you!

java.lang.NullPointerException
        at com.xeiam.xchange.bitstamp.service.BitstampDigest.digestParams(BitstampDigest.java:44)
        at si.mazi.rescu.Params.digestAll(Params.java:199)
        at si.mazi.rescu.RestInvocation.create(RestInvocation.java:142)
        at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:110)
        at com.sun.proxy.$Proxy14.getBalance(Unknown Source)
        at com.xeiam.xchange.bitstamp.service.polling.BitstampAccountServiceRaw.getBitstampBalance(BitstampAccountServiceRaw.java:45)
        at com.xeiam.xchange.bitstamp.service.polling.BitstampAccountService.getAccountInfo(BitstampAccountService.java:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
        at py4j.Gateway.invoke(Gateway.java:259)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:209)
        at java.lang.Thread.run(Thread.java:745)

**Comment by iwuvjhdva** [comment]
sorry, my fault, Bitstamp requires user name to be set
