### ISSUE TITLE
BTC-e handshake exception after installing certificate

### ISSUE THREAD

**Issue by Muffon** [timmolter/XChange#1079]
Hello, has anyone tried to install certificate for btc-e.com into TrustStore? I have followed instructions here https://github.com/timmolter/XChange/wiki/Installing-SSL-Certificates-into-TrustStore and it worked well for Kraken, OKCoin, BitsStamp and others, but not for the BTC-e. Ceritifcate was accepted but when I tried to connect I have got
```java 
 at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1043)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1511)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
        at si.mazi.rescu.HttpTemplate.receive(HttpTemplate.java:106)
        at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:150)
        at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:114)
        at com.sun.proxy.$Proxy22.getTicker(Unknown Source)
        at com.xeiam.xchange.btce.v3.service.polling.BTCEMarketDataServiceRaw.getBTCETicker(BTCEMarketDataServiceRaw.java:35)
        at com.xeiam.xchange.btce.v3.service.polling.BTCEMarketDataService.getTicker(BTCEMarketDataService.java:35)
        at org.onlab.arbitrader.ticker.TickerRunnable.getLastTicker(TickerRunnable.java:95)
        at org.onlab.arbitrader.ticker.TickerRunnable.run(TickerRunnable.java:48)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:744)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
        at sun.security.validator.Validator.validate(Validator.java:260)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1351)


```

**Comment by Muffon** [comment]
Well, it works. I had a typo in my path.
