### ISSUE TITLE
com.xeiam.xchange.coinbaseex: getCoinbaseExAccountInfo error 400

### ISSUE THREAD

**Issue by GratefulTony** [timmolter/XChange#1159]
having trouble getting coinbaseex acct. infos/ balance, looks like an error 400.

```
xception in thread "main" java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy12.getAccounts(Unknown Source)
	at com.xeiam.xchange.coinbaseex.service.polling.CoinbaseExAccountServiceRaw.getCoinbaseExAccountInfo(CoinbaseExAccountServiceRaw.java:17)
	at com.xeiam.xchange.coinbaseex.service.polling.CoinbaseExAccountService.getAccountInfo(CoinbaseExAccountService.java:24)
	(my traceback)
(more my traceback...)

Caused by: si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 400
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:106)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:137)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:125)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:104)
```

**Comment by jheusser** [comment]
@GratefulTony do other authenticated calls work? Can you set Rescu logging to `TRACE` for more error output

**Comment by GratefulTony** [comment]
I haven't tested other methods exhaustively, but I can get an order book. I'll do further tests tonight.

**Comment by gyanengle** [comment]
@GratefulTony I'm seeing the same thing... Did you find anything?

**Comment by GratefulTony** [comment]
I worked on it for a while but never got it working... pivoted for a different lib that did work for Coinbase.

**Comment by gyanengle** [comment]
What lib was that, do you mind telling?

**Comment by GratefulTony** [comment]
https://github.com/coinbase/coinbase-java

**Comment by gyanengle** [comment]
Thank you, sir

**Comment by diogoribeiro** [comment]
Did someone find anything about this error?
I'm having the same error

**Comment by diogoribeiro** [comment]
I fixed this issue getting GDAX credentials.
It seems that coinbase is now part of GDAX.

**Comment by timmolter** [comment]
coinbaseex is now gdax in XChange.
