### ISSUE TITLE
HitBTC getTradeHistory throws null expection if you have trades.

### ISSUE THREAD

**Issue by dimecoin** [timmolter/XChange#1179]
If you have zero trades, then this works fine (returns 0 trades).  But if you have 1 or more trades on exchange, then it throws a null.  Rest of trade services seem to work fine for this exchange.		

**Code**

    HitbtcTradeHistoryParams params = new HitbtcTradeHistoryParams(0,1000);
    params.setCurrencyPair(CurrencyPair.LTC_BTC);
    trades = tradeService.getTradeHistory(params);
			
**Exception**

    Exception in thread "main" java.lang.NullPointerException
	at com.xeiam.xchange.hitbtc.HitbtcAdapters.adaptTradeHistory(HitbtcAdapters.java:269)
	at com.xeiam.xchange.hitbtc.service.polling.HitbtcTradeService.getTradeHistory(HitbtcTradeService.java:86)
	at com.dimecoingames.tradesystem.feed.ExchangeFeed.getTrades(ExchangeFeed.java:273)
	at com.dimecoingames.tradesystem.feed.TestTrades.main(TestTrades.java:19

**Comment by rafalkrupinski** [comment]
Hi,

looks like it's missing metadata. You need to call `Exchange.remoteInit()` first.

Rafał

**Comment by dimecoin** [comment]
Thanks Rafal, I can confirm this works.

**Comment by dimecoin** [comment]
Should Exchange.remoteInit() be called for all feeds or just hitbtc?

**Comment by rafalkrupinski** [comment]
It's exchange-specific, but it won't hurt to call it on every one.

**Comment by dimecoin** [comment]
This issue can be closed; it is fixed if `Exchange.remoteInit()` is called.
