### ISSUE TITLE
Error when create ticker

### ISSUE THREAD

**Issue by yiranliu** [timmolter/XChange#1246]
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	Syntax error on token "}", delete this token

	at com.xeiam.xchange.dto.marketdata.Ticker$Builder.currencyPair(Ticker.java:156)
	at com.xeiam.xchange.clevercoin.CleverCoinAdapters.adaptTicker(CleverCoinAdapters.java:154)
	at com.xeiam.xchange.clevercoin.service.polling.CleverCoinMarketDataService.getTicker(CleverCoinMarketDataService.java:32)
	at com.xeiam.xchange.examples.clevercoin.marketdata.CleverCoinTickerDemo.generic(CleverCoinTickerDemo.java:33)
	at com.xeiam.xchange.examples.clevercoin.marketdata.CleverCoinTickerDemo.main(CleverCoinTickerDemo.java:27)

**Comment by timmolter** [comment]
Doesn't make sense because the entire project compiles just fine. We have a CI server to always double check everything committed to the repo. Also you should bump up to 3.0.0 or 3.0.1-SNAPSHOT.

**Comment by yiranliu** [comment]
updated my pom from com.xieam to org.knowm, this one fixed
Thanks
