### ISSUE TITLE
New rescu 1.9 broke poloniex module.

### ISSUE THREAD

**Issue by ezhik97** [timmolter/XChange#1291]
New rescu 1.9 dependency lead an exception while parse POLONIEX JSON response. Move down to version 1.8.2-SNAPSHOT of rescu fixed the issue.

`16:38:23.723 [main] WARN  si.mazi.rescu.ResponseReader - Noncritical error parsing error output: {"1CR":{"id":1,"name":"1CRedit","txFee":"0.01000000","minConf":3,"depositAddress":null,"disabled":0,...
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "1CR" (class org.knowm.xchange.poloniex.PoloniexException), not marked as ignorable (3 known properties: "error", "cause", "httpStatusCode"])
 at [Source: java.io.StringReader@7ce69770; line: 1, column: 36643] (through reference chain: org.knowm.xchange.poloniex.PoloniexException["1CR"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51) ~[jackson-databind-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:817) ~[jackson-databind-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:958) ~[jackson-databind-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1324) ~[jackson-databind-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1278) ~[jackson-databind-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:452) ~[jackson-databind-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:66) ~[jackson-databind-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:142) ~[jackson-databind-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3564) ~[jackson-databind-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2618) ~[jackson-databind-2.5.4.jar:2.5.4]
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53) ~[rescu-1.9.0-SNAPSHOT.jar:na]
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58) ~[rescu-1.9.0-SNAPSHOT.jar:na]
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82) ~[rescu-1.9.0-SNAPSHOT.jar:na]
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169) [rescu-1.9.0-SNAPSHOT.jar:na]
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157) [rescu-1.9.0-SNAPSHOT.jar:na]
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120) [rescu-1.9.0-SNAPSHOT.jar:na]`

**Comment by zholmes1** [comment]
@mmazi The problem appears to be that Poloniex have added fields to their response in "returnCurrencies" method.

https://poloniex.com/public?command=returnCurrencies

Our DTO did not have these, and rescu threw an exception because the fields were not declared as "ignorable." This clearly should not be how rescu works, because APIs can add fields all the time and it definitely should not break code.

I resolved this issue just by adding the 3 missing fields to the DTO, but I think that this is something that needs to be addressed in rescu.

**Comment by ezhik97** [comment]
Does the fix builded in current version of 1.9.0-SNAPSHOT? Because of the issue still exists. It seems that rescu can't parse field '1CR' - this is currency name and the response has many such fields and new currencies will be added soon.

**Comment by zholmes1** [comment]
It only has trouble with "1CR" once it has decided to parse the response as
an error because of the additional fields not marked as ignorable. Look at
the two sets of fields it is looking for and you'll see what I mean. Yes,
my fix works in the current version of rescu. Look at my pull request and
you can just grab the file if you need it quickly.

**Comment by mmazi** [comment]
The problem was due to Jackson's `FAIL_ON_UNKNOWN_PROPERTIES` not being set to `false`. My mistake when upgrading rescu in XChange; `JacksonObjectMapperFactory::configureObjectMapper` should always call `super`. Fixed now.

**Comment by ezhik97** [comment]
Great! Thanks.
