### ISSUE TITLE
OkCoin Streaming Example throws java.lang.NullPointerException

### ISSUE THREAD

**Issue by quorak** [timmolter/XChange#1316]
Hey there,

just a quick note. It tried to get the `org.knowm.xchange.examples.okcoin.streaming.OkCoinSocketIODemo` running. But encountered multiple issues. Most obvious was the following Exception

```
java.lang.NullPointerException
	at org.knowm.xchange.okcoin.service.streaming.OkCoinWebSocketService.parseTicker(OkCoinWebSocketService.java:84)
	at org.knowm.xchange.okcoin.service.streaming.OkCoinWebSocketService.parseMarketData(OkCoinWebSocketService.java:78)
	at org.knowm.xchange.okcoin.service.streaming.OkCoinWebSocketService.onReceive(OkCoinWebSocketService.java:51)
	at org.knowm.xchange.okcoin.service.streaming.WebSocketClientHandler.channelRead0(WebSocketClientHandler.java:75)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:971)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:854)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:886)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:834)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

which is probably thrown at the initial success event of okcoins Webhook API. The code tries to parse `{"channel":"ok_btcusd_ticker","success":"true"}` but cannot find the `data` attribute, which is obiously only available on events with payload.

But what seems more disturbing to me, was the continous connect disconnect events

```
10:54:52.912 [default] [nioEventLoopGroup-52-1] WARN  o.k.x.o.s.s.WebSocketClientHandler - WebSocket Client disconnected! 
10:55:01.563 [default] [nioEventLoopGroup-53-1] DEBUG o.k.x.o.s.s.WebSocketClientHandler - WebSocket Client connected! 
10:55:01.871 [default] [nioEventLoopGroup-53-1] WARN  o.k.x.o.s.s.WebSocketClientHandler - WebSocket Client disconnected! 
10:55:10.582 [default] [nioEventLoopGroup-54-1] DEBUG o.k.x.o.s.s.WebSocketClientHandler - WebSocket Client connected! 
10:55:10.866 [default] [nioEventLoopGroup-54-1] WARN  o.k.x.o.s.s.WebSocketClientHandler - WebSocket Client disconnected! 
....
```

I don't know if these problems are related.
great library guys. your work is much appreciated. hope this helps to improve even more.

**Comment by jheusser** [comment]
@quorak thanks for reporting, this is partially to do with the streaming code being unmaintained but also due to Chinese connectivity. I suggest you to use REST polling instead.

**Comment by timmolter** [comment]
Streaming now dropped in this lib: https://github.com/timmolter/XChange/issues/1235
