### ISSUE TITLE
Test failure on BTC China

### ISSUE THREAD

**Issue by haiqu** [timmolter/XChange#1319]
[INFO] XChange BTC China .................................. FAILURE [  0.764 s]
[INFO] XChange BTCE ....................................... SKIPPED
[INFO] XChange BTCMarkets ................................. SKIPPED
[INFO] XChange BtcTrade ................................... SKIPPED
[INFO] XChange BTER ....................................... SKIPPED
[INFO] XChange CampBX ..................................... SKIPPED
[INFO] XChange Cex.io ..................................... SKIPPED
[INFO] XChange CHBTC ...................................... SKIPPED
[INFO] XChange CleverCoin ................................. SKIPPED
[INFO] XChange Coinbase ................................... SKIPPED
[INFO] XChange Coinbase (Exchange) ........................ SKIPPED
[INFO] XChange Coinmate ................................... SKIPPED
[INFO] XChange Cointrader ................................. SKIPPED
[INFO] XChange CryptoFacilities ........................... SKIPPED
[INFO] XChange Cryptonit .................................. SKIPPED
[INFO] XChange EmpoEX ..................................... SKIPPED
[INFO] XChange Open Exchange Rates ........................ SKIPPED
[INFO] XChange Kraken ..................................... SKIPPED
[INFO] XChange ItBit ...................................... SKIPPED
[INFO] XChange Independent Reserve ........................ SKIPPED
[INFO] XChange LakeBTC .................................... SKIPPED
[INFO] XChange Loyalbit ................................... SKIPPED
[INFO] XChange Hitbtc ..................................... SKIPPED
[INFO] XChange Paymium .................................... SKIPPED
[INFO] XChange Poloniex ................................... SKIPPED
[INFO] XChange OKCoin ..................................... SKIPPED
[INFO] XChange Mercado Bitcoin ............................ SKIPPED
[INFO] XChange Jubi ....................................... SKIPPED
[INFO] XChange taurus ..................................... SKIPPED
[INFO] XChange Quoine ..................................... SKIPPED
[INFO] XChange Ripple ..................................... SKIPPED
[INFO] XChange The Rock Trading ........................... SKIPPED
[INFO] XChange Gatecoin ................................... SKIPPED
[INFO] XChange meXBT ...................................... SKIPPED
[INFO] XChange Vircurex ................................... SKIPPED
[INFO] XChange Examples ................................... SKIPPED
[INFO] XChange Gemini ..................................... SKIPPED
[INFO] XChange QuadrigaCx ................................. SKIPPED
[INFO] XChange Vaultoro ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:43 min
[INFO] Finished at: 2016-10-14T19:21:45+10:00
[INFO] Final Memory: 13M/35M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project xchange-btcchina: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project xchange-btcchina: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.RuntimeException: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
        at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.close(ForkClient.java:257)
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:301)
        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:116)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:740)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAllProviders(AbstractSurefireMojo.java:682)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:648)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:586)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :xchange-btcchina

**Comment by haiqu** [comment]
System: Windows 7, Maven 3.3.9, Oracle Java 1.8.0_101

**Comment by haiqu** [comment]
The only obvious difference I can think of is that 32-bit Windows has a hard 3GB memory limit. Maybe the tools are demanding more than this. I've seen it before in Java.

**Comment by haiqu** [comment]
`mvn clean test` now runs cleanly since the last commit. You can close this one. Many thanks.
