### ISSUE TITLE
Cannot connect to exchange, I get SSLHandshakeException

### ISSUE THREAD

**Issue by radumiron** [timmolter/XChange#1330]
Hi all,

I am trying to connect to BTC-E / Kraken through a proxy. When creating the exchange instance, I get the following exception:

> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'XChangeTrading': Invocation of init method failed; nested exception is org.knowm.xchange.exceptions.ExchangeException: javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1575)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1128)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1056)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566)
	... 24 common frames omitted
Caused by: org.knowm.xchange.exceptions.ExchangeException: javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:115)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:89)
	at com.github.bitcharts.trading.XChangeTrading.initServices(XChangeTrading.java:57)
	at com.github.bitcharts.trading.XChangeTrading.initTradingObject(XChangeTrading.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:310)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	... 36 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at si.mazi.rescu.HttpTemplate.receive(HttpTemplate.java:122)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:156)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120)
	at com.sun.proxy.$Proxy70.getAssetPairs(Unknown Source)
	at org.knowm.xchange.kraken.service.polling.KrakenMarketDataServiceRaw.getKrakenAssetPairs(KrakenMarketDataServiceRaw.java:84)
	at org.knowm.xchange.kraken.KrakenExchange.remoteInit(KrakenExchange.java:53)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:111)
	... 46 common frames omitted

I'm connecting to the exchange through a proxy, setup like this:
`System.setProperty("http.proxyHost", Global.PROXY_SERVER_HOST);`
`System.setProperty("http.proxyPort", Global.PROXY_SERVER_PORT);`

The connection succeeds when running it from outside the proxy.
Do you know what might be the issue?

Thanks,
Radu

**Comment by jheusser** [comment]
Try perhaps https://github.com/timmolter/XChange/wiki/Installing-SSL-Certificates-into-TrustStore
