### ISSUE TITLE
Quoine: API Authentication fails for AccountInfoDemo

### ISSUE THREAD

**Issue by matthiasamberg** [timmolter/XChange#1343]
Hello all,

I'm trying to run the demo from xchange-examples...quoine.account.AccountInfoDemo.java
I've added my ID and SECRET to empty placeholders in QuoineExamplesUtils.java class
however I get an 401  API Authentication failed error back.

My lines in QuoineExamplesUtils look similar (keys changed) to this:
```
		exSpec.getExchangeSpecificParameters().put(QuoineExchange.KEY_USER_ID, "11512");
		exSpec.getExchangeSpecificParameters().put(QuoineExchange.KEY_USER_SECRET, "bQ9weVcbel576E2122SOzjKJZg3c0KW2zd4pq5GTVjT0pwv6A+Omp/MeuVpDoD25YfaehCx/xd0SknZt1==");
```

The above are the keys I got from the (enabled) api settings page in my quoine account.
Is there something I do wrong or is the code/api currently somewhat broken?

Thanks in advance and below the full exception I get:

```
Exception in thread "main" org.knowm.xchange.exceptions.ExchangeException: API Authentication failed
	at org.knowm.xchange.quoine.service.polling.QuoineAccountServiceRaw.getQuoineAccountInfo(QuoineAccountServiceRaw.java:30)
	at org.knowm.xchange.quoine.service.polling.QuoineAccountService.getAccountInfo(QuoineAccountService.java:44)
	at org.knowm.xchange.examples.quoine.account.AccountInfoDemo.generic(AccountInfoDemo.java:30)
	at org.knowm.xchange.examples.quoine.account.AccountInfoDemo.main(AccountInfoDemo.java:24)
Caused by: si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 401
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120)
	at com.sun.proxy.$Proxy12.getAccountInfo(Unknown Source)
	at org.knowm.xchange.quoine.service.polling.QuoineAccountServiceRaw.getQuoineAccountInfo(QuoineAccountServiceRaw.java:28)
```

**Comment by jheusser** [comment]
Looks like Quoine changed their authentication to use [JWT](https://jwt.io/)

**Comment by jheusser** [comment]
@matthiasamberg do you want to test again? Quoine has been updated to the latest version. I'm closing this for now.

**Comment by npomfret** [comment]
@matthiasamberg did you resolve this?  I'm getting a 401 from some endpoints but not others.
