### ISSUE TITLE
Invalid Nonce with Kraken

### ISSUE THREAD

**Issue by Ri5nV5** [timmolter/XChange#1347]
Good morning I'm trying to run the example and I always get the same nonce error.
How can I fix the problem.
Thank you

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.knowm.xchange.exceptions.NonceException: **EAPI:Invalid nonce**
	at org.knowm.xchange.kraken.service.polling.KrakenBasePollingService.checkResult(KrakenBasePollingService.java:70)
	at org.knowm.xchange.kraken.service.polling.KrakenAccountServiceRaw.getKrakenBalance(KrakenAccountServiceRaw.java:53)
	at org.knowm.xchange.kraken.service.polling.KrakenAccountService.getAccountInfo(KrakenAccountService.java:28)
	at test.KrakenAccountDemo.generic(KrakenAccountDemo.java:30)
	at test.KrakenAccountDemo.main(KrakenAccountDemo.java:24)

**Comment by dozd** [comment]
You must be doing something wrong. KrakenExchange is working for me fine - account info as well as trading api.

**Comment by mmazi** [comment]
Have you used the same API key you are using here in some other (non-XChange-based) application? If you have, the app may have already used a bigger nonce than what XChange tries to use, so XChange's calls will always fail.

If this is the case, then the solution is to use a fresh API key for the example.

**Comment by npomfret** [comment]
@dozd is there a trick to getting the Kraken exchange working?  I'm creating the exchange like this:

        KrakenExchange exchange = (KrakenExchange) ExchangeFactory.INSTANCE.createExchange(
                KrakenExchange.class.getName(),
                null,
                null,
                apiKey,
                privateKey);
        AccountService accountService = exchange.getAccountService();
        AccountInfo accountInfo = accountService.getAccountInfo();


And I'm getting this error:

```
Exception in thread "main" org.knowm.xchange.exceptions.ExchangeException: [EAPI:Invalid key]
	at org.knowm.xchange.kraken.service.KrakenBaseService.checkResult(KrakenBaseService.java:74)
	at org.knowm.xchange.kraken.service.KrakenAccountServiceRaw.getKrakenBalance(KrakenAccountServiceRaw.java:58)
	at org.knowm.xchange.kraken.service.KrakenAccountService.getAccountInfo(KrakenAccountService.java:42)

```

**Comment by e1ektr0** [comment]
@npomfret  Try create new api keys. Possible you broke it(used big nonce) from other app or used it on machine with incorrect time.
