### ISSUE TITLE
Some tests output errors/warnings (tho don't seem to actually fail?) when doing "mvn clean install" on clean github checkout

### ISSUE THREAD

**Issue by abletaz** [timmolter/XChange#1480]
not sure if this points to anything needing cleaning-up or not, but mentioning just in case ......

Running org.knowm.xchange.bleutrade.BleutradeUtilsTest
java.text.ParseException: Unparseable date: "yyyy-MM-dd"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at org.knowm.xchange.bleutrade.BleutradeUtils.toDate(BleutradeUtils.java:36)
	at org.knowm.xchange.bleutrade.BleutradeUtilsTest.shouldConvertStringToDate(BleutradeUtilsTest.java:26)

java.text.ParseException: Unparseable date: ""
	at java.text.DateFormat.parse(DateFormat.java:366)
	at org.knowm.xchange.bleutrade.BleutradeUtils.toDate(BleutradeUtils.java:36)
	at org.knowm.xchange.bleutrade.BleutradeUtilsTest.shouldConvertStringToDate(BleutradeUtilsTest.java:27)

Running org.knowm.xchange.bleutrade.dto.BleutradeAdaptersTest
[main] WARN org.knowm.xchange.dto.account.Balance - 15.49843675 = total != available + frozen - borrowed + loaned + withdrawing + depositing = 13.98901996
[main] WARN org.knowm.xchange.dto.account.Balance - 15.49843675 = total != available + frozen - borrowed + loaned + withdrawing + depositing = 13.98901996

**Comment by timmolter** [comment]
Fixed. I made the `toDate` method return null instead in accordance with the XChange expected behavior. I also removed the exception being printed out.
