### ISSUE TITLE
LakeBTC - 404 getting account

### ISSUE THREAD

**Issue by npomfret** [timmolter/XChange#1511]
Calling `exchange.getAccountService().getAccountInfo();` results in:

```
Caused by: si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 404
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120)
	at com.sun.proxy.$Proxy13.getAccountInfo(Unknown Source)
	at org.knowm.xchange.lakebtc.service.LakeBTCAccountServiceRaw.getLakeBTCAccountInfo(LakeBTCAccountServiceRaw.java:25)
	at org.knowm.xchange.lakebtc.service.LakeBTCAccountService.getAccountInfo(LakeBTCAccountService.java:36)
```

@timmolter @jamespedwards42  any ideas?

**Comment by jamespedwards42** [comment]
This was implemented against V1 of their API, which they dropped support for as of April 2017. See https://www.lakebtc.com/s/api_v2.  Looks like the data modeling will need to be updated as well to upgrade to version 2.
