### ISSUE TITLE
[Gemini] deserialisation exception

### ISSUE THREAD

**Issue by ymyronov** [timmolter/XChange#1543]
Hello, trying to use xchange 4.2 GeminiExchange:
```
Exchange gemini = ExchangeFactory.INSTANCE.createExchange(GeminiExchange.class.getName());
Ticker tickerGemini = gemini.getMarketDataService().getTicker(CurrencyPair.BTC_USD);
System.out.println(tickerGemini.getBid());
```

Seems to be working for other exchanges, but for Gemini I get an exception:
```
Caused by: org.knowm.xchange.gemini.v1.dto.GeminiException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:274)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:224)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:135)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:471)
	at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:65)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2871)
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53)
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58)
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120)
	at com.sun.proxy.$Proxy13.getTicker(Unknown Source)
	at org.knowm.xchange.gemini.v1.service.GeminiMarketDataServiceRaw.getGeminiTicker(GeminiMarketDataServiceRaw.java:42)

```

**Comment by timmolter** [comment]
please try the latest develop branch. I bet it's already fixed.

**Comment by ymyronov** [comment]
Thanks for quick reply, yes it is working in 4.2.1 snapshot as well as develop.
