### ISSUE TITLE
Coinbase bind issue

### ISSUE THREAD

**Issue by salamtura** [timmolter/XChange#1549]
Hello, 

I got this issue this morning. Any pointers please

com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164) ~[jackson-databind-2.4.1.1.jar:2.4.1.1]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3095) ~[jackson-databind-2.4.1.1.jar:2.4.1.1]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3036) ~[jackson-databind-2.4.1.1.jar:2.4.1.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2160) ~[jackson-databind-2.4.1.1.jar:2.4.1.1]
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53) ~[rescu-1.9.0.jar:na]
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58) ~[rescu-1.9.0.jar:na]
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82) ~[rescu-1.9.0.jar:na]
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169) [rescu-1.9.0.jar:na]
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157) [rescu-1.9.0.jar:na]
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120) [rescu-1.9.0.jar:na]
	at com.sun.proxy.$Proxy120.generateReceiveAddress(Unknown Source) [na:na]
	at org.knowm.xchange.coinbase.service.CoinbaseAccountServiceRaw.generateCoinbaseReceiveAddress(CoinbaseAccountServiceRaw.java:170) [xchange-coinbase-4.2.0.jar:na]
	at org.knowm.xchange.coinbase.service.CoinbaseAccountService.generateCoinbaseReceiveAddress(CoinbaseAccountService.java:19) [xchange-coinbase-4.2.0.jar:na]

**Comment by timmolter** [comment]
try the latest snapshot jar or run the latest code on the develop branch please.

**Comment by timmolter** [comment]
Also the Coinbase impl. uses the deprecated V1 API. Try the GDAx impl.
