### ISSUE TITLE
Poloniex bookdepth too large to parse

### ISSUE THREAD

**Issue by douggie** [timmolter/XChange#1579]
Hi,

it would seem xchnage is making the following get request for book data https://poloniex.com/public?command=returnOrderBook&currencyPair=BTC_ETH&depth=999999, giving the largest level of depth that resuc does not seem to be able to read in line by line in sufficient time.

Should we just limit to depth to top 100 orders?

{
2017-07-02 16:07:37 [pool-22-thread-5] INFO  org.cryptocoinpartners.xchangeData - XchangeData:getTrades Unabel to get trade for market POLONIEX:ETH.BTC pair ETH/BTC.  Failure 1 of 10. 
java.io.IOException: Premature EOF
	at sun.net.www.http.ChunkedInputStream.readAheadBlocking(ChunkedInputStream.java:565) ~[na:1.7.0_60-ea]
	at sun.net.www.http.ChunkedInputStream.readAhead(ChunkedInputStream.java:609) ~[na:1.7.0_60-ea]
	at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:696) ~[na:1.7.0_60-ea]
	at java.io.FilterInputStream.read(FilterInputStream.java:133) ~[na:1.7.0_60-ea]
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3053) ~[na:1.7.0_60-ea]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283) ~[na:1.7.0_60-ea]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325) ~[na:1.7.0_60-ea]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177) ~[na:1.7.0_60-ea]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[na:1.7.0_60-ea]
	at java.io.BufferedReader.fill(BufferedReader.java:154) ~[na:1.7.0_60-ea]
	at java.io.BufferedReader.readLine(BufferedReader.java:317) ~[na:1.7.0_60-ea]
	at java.io.BufferedReader.readLine(BufferedReader.java:382) ~[na:1.7.0_60-ea]
	at si.mazi.rescu.HttpTemplate.readInputStreamAsEncodedString(HttpTemplate.java:224) ~[rescu-1.9.0.jar:na]
	at si.mazi.rescu.HttpTemplate.receive(HttpTemplate.java:127) ~[rescu-1.9.0.jar:na]
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:156) ~[rescu-1.9.0.jar:na]
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120) ~[rescu-1.9.0.jar:na]
	at com.sun.proxy.$Proxy103.getOrderBook(Unknown Source) ~[na:na]
	at org.knowm.xchange.poloniex.service.PoloniexMarketDataServiceRaw.getPoloniexDepth(PoloniexMarketDataServiceRaw.java:108) ~[classes/:na]
	at org.knowm.xchange.poloniex.service.PoloniexMarketDataService.getOrderBook(PoloniexMarketDataService.java:55) ~[classes/:na]
	at org.cryptocoinpartners.module.xchange.XchangeData.getBook(XchangeData.java:336) ~[classes/:na]
	at org.cryptocoinpartners.module.xchange.XchangeData$FetchTradesCallable.call(XchangeData.java:420) [classes/:na]
	at org.cryptocoinpartners.module.xchange.XchangeData$FetchTradesCallable.call(XchangeData.java:1) [classes/:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_60-ea]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_60-ea]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_60-ea]

**Comment by douggie** [comment]
I see we have a param we can pass, to limit the depth, great!

**Comment by timmolter** [comment]
I've never seen that error using that default param.
