### ISSUE TITLE
Poloinex Exchange always returning no data for [CRYPTO]-fiat pairs

### ISSUE THREAD

**Issue by mrwillis** [timmolter/XChange#1583]
Hi all,

I seem to never be able to get data for Poloinex and always an `ExchangeException`. Here's my code:

``` java
  try {
            Ticker poloinex = this.PoloniexMarketDataService.getTicker(CurrencyPair.BTC_USD);
            quotes.put("Poloniex", new Quote(poloinex.getBid(), poloinex.getAsk()));
        } catch (IOException e) {
            Logger.warn("Poloinex data not available");
        }
```

And for the last three days, I've been getting 

```
Exception in thread "main" org.knowm.xchange.exceptions.ExchangeException: BTC/USD not available
	at org.knowm.xchange.poloniex.service.PoloniexMarketDataServiceRaw.getPoloniexTicker(PoloniexMarketDataServiceRaw.java:83)
	at org.knowm.xchange.poloniex.service.PoloniexMarketDataService.getTicker(PoloniexMarketDataService.java:36)
	at ArbMonitor.getCurrentQuotes(ArbMonitor.java:111)
```

I've tried other fiat currencies, no good. It seems like crypto-crypto pairs are fine though.

Thanks for the help :)

**Comment by timmolter** [comment]
Try this for the `CurrencyPair` : `new CurrencyPair("BTC", "USDT");`

**Comment by ezhik97** [comment]
Yes, there is a typo - Poloniex does not have 'USD' currency, they has 'USDT'. For me getTicker() for all poloniex pairs works fine. I think that we can just close this issue.
