### ISSUE TITLE
Deserialize Exception Quering Kraken Trailing-Stop closed orders

### ISSUE THREAD

**Issue by cvinacua** [timmolter/XChange#1626]
When querying Kraken Closed Orders, if there is an order with price in percentage (like "+2.0%) deserialization fails like this:

si.mazi.rescu.HttpStatusIOException: Can not deserialize value of type java.math.BigDecimal from String "+2.0000%": not a valid representation
 at [Source: {"error":[],"result":{"closed":{"O74UTU-RRJAP-4N5I7H":{"refid":null,"userref":null,"status":"canceled","reason":"User canceled","opentm":1500619912.4519,"closetm":1500620605.9801,"starttm":0,"expiretm":0,"descr":{"pair":"ETHXBT","type":"sell","ordertype":"stop-loss-limit","price":"0.081436","price2":"0.080622","leverage":"none","order":"sell 1.00000000 ETHXBT @ stop loss 0.081436 -> limit 0.080622","close":"close position @ limit -1.0000%"},"vol":"1.00000000","vol_exec":"0.00000000","cost":"0.000000","fee":"0.000000","price":"0.000000","misc":"","oflags":"fciq"},"OHCIYA-27DQZ-BXGT6S":{"refid":null,"userref":null,"status":"canceled","reason":"User canceled","opentm":1500619692.5724,"closetm":1500620656.1296,"starttm":0,"expiretm":0,"descr":{"pair":"ETHEUR","type":"sell","ordertype":"stop-loss-limit","price":"192.95521","price2":"191.02566","leverage":"none","order":"sell 1.00000000 ETHEUR @ stop loss 192.95521 -> limit 191.02566","close":"close position @ limit -1.0000%"},"vol":"1.00000000","vol_exec":"0.00000000","cost":"0.00000","fee":"0.00000","price":"0.00000","misc":"","oflags":"fciq"}
....
....

line: 1, column: 1372] (through reference chain: org.knowm.xchange.kraken.dto.trade.results.KrakenClosedOrdersResult["result"]->org.knowm.xchange.kraken.dto.trade.results.KrakenClosedOrdersResult$KrakenClosedOrders["closed"]->java.util.LinkedHashMap["OCVZSA-NZ3BT-4YJ4RT"]->org.knowm.xchange.kraken.dto.trade.KrakenOrder["descr"]->org.knowm.xchange.kraken.dto.trade.KrakenOrderDescription["price"])
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120)
	at com.sun.proxy.$Proxy21.closedOrders(Unknown Source)
	at org.knowm.xchange.kraken.service.KrakenTradeServiceRaw.getKrakenClosedOrders(KrakenTradeServiceRaw.java:63)
	at com.chema.kraken.service.MyKrakenService.getRecentClosedOrders(MyKrakenService.java:320)
	at com.chema.kraken.Blocker.run(Blocker.java:87)
	at com.chema.kraken.Blocker.main(Blocker.java:75)

....
....

line: 1, column: 1372] (through reference chain: org.knowm.xchange.kraken.dto.trade.results.KrakenClosedOrdersResult["result"]->org.knowm.xchange.kraken.dto.trade.results.KrakenClosedOrdersResult$KrakenClosedOrders["closed"]->java.util.LinkedHashMap["OCVZSA-NZ3BT-4YJ4RT"]->org.knowm.xchange.kraken.dto.trade.KrakenOrder["descr"]->org.knowm.xchange.kraken.dto.trade.KrakenOrderDescription["price"])
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120)
	at com.sun.proxy.$Proxy21.closedOrders(Unknown Source)
	at org.knowm.xchange.kraken.service.KrakenTradeServiceRaw.getKrakenClosedOrders(KrakenTradeServiceRaw.java:63)

**Comment by CHUANGPEIFENG** [comment]
〈0

2017年7月21日 15:15，"Chema Vinacua" <notifications@github.com>寫道：

**Comment by CHUANGPEIFENG** [comment]
我已與您共用一份文件：

  Vegas Slot Machine
http://drive.google.com/file/d/0B6wWSVfNK1GmZ2FrOGtKLU9ZUHM/view?usp=sharing&invite=CP2imegJ&ts=5988dd88

這並不是附件，而是儲存在網路上的檔案。如要開啟這個檔案，只需點選上方的連結即 
可。
