### ISSUE TITLE
JSON parse error in getOpenOrders from Bitfinex

### ISSUE THREAD

**Issue by Denebulas** [timmolter/XChange#1649]
When I call getOpenOrders after connecting and placing a limit order I get:

107845 [MAIN] WARN si.mazi.rescu.ResponseReader - Noncritical error parsing error output: [{"id":3221715321,"cid":36986548262,"cid_date":"2017-07-31","gid":null,"symbol":"btcusd","exchange":"bitfinex","price":"2755.0","avg_execution_price":"0.0","side":"sell","type":"exchange limit","times...

The cause seems a long value into a integer variable because the debug is:

si.mazi.rescu.HttpStatusIOException: Numeric value (3221715321) out of range of int
 at [Source: [{"id":3221715321,"cid":36986548262,"cid_date":"2017-07-31","gid":null,"symbol":"btcusd","exchange":"bitfinex","price":"2755.0","avg_execution_price":"0.0","side":"sell","type":"exchange limit","timestamp":"1501496187.0","is_live":true,"is_cancelled":false,"is_hidden":false,"oco_order":null,"was_forced":false,"original_amount":"0.01","remaining_amount":"0.01","executed_amount":"0.0","src":"api"}]; line: 1, column: 18]
 at [Source: [{"id":3221715321,"cid":36986548262,"cid_date":"2017-07-31","gid":null,"symbol":"btcusd","exchange":"bitfinex","price":"2755.0","avg_execution_price":"0.0","side":"sell","type":"exchange limit","timestamp":"1501496187.0","is_live":true,"is_cancelled":false,"is_hidden":false,"oco_order":null,"was_forced":false,"original_amount":"0.01","remaining_amount":"0.01","executed_amount":"0.0","src":"api"}]; line: 1, column: 8] (through reference chain: java.lang.Object[][0]->org.knowm.xchange.bitfinex.v1.dto.trade.BitfinexOrderStatusResponse["id"])
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120)
	at com.sun.proxy.$Proxy12.activeOrders(Unknown Source)
	at org.knowm.xchange.bitfinex.v1.service.BitfinexTradeServiceRaw.getBitfinexOpenOrders(...

I am not able to fix the problem myself and also the field seems a long value ...

**Comment by npomfret** [comment]
That's a strange one.  The id is modelled as a long, not an int.  It's just a warning so can perhaps be ignored for now.  

IMO ids should never be modelled as numbers.  Just because they contain only numeric values doesn't mean they are numbers (it doesn't make sense to add them together for example).  Personally I'd like to see all ids here modelled as strings.

**Comment by timmolter** [comment]
@Denebulas Can you try out the latest snapshot jar? Perhaps you are using an old version.

**Comment by timmolter** [comment]
@npomfret The `Order` class has ID as a String. 
```
  /**
   * An identifier that uniquely identifies the order
   */
  private final String id;
```

I agree with you that the raw DTOs should treat IDs as Strings too.

**Comment by timmolter** [comment]
However, in API docs, it often says ID=Integer, so making the Raw DTO ID as an int also makes sense. I dunno...

**Comment by npomfret** [comment]
I think if an _int_ id is specified in an API (in some json to go over the wire) that conversion should be done at the last minute.  In some cases it might not even be needed, such as in a URL - an _int_ and a _string_ would look  the same.

**Comment by Denebulas** [comment]
Yes it's working with the snapshots. 
Thank you very much.
