### ISSUE TITLE
Bittrex - concurrency issue when calling getTrades()

### ISSUE THREAD

**Issue by keith-f** [timmolter/XChange#1664]
I'm occasionally getting strange behaviour when calling the Bittrex implementation of `getTrades()`, but only when using more than one thread to poll the trades from multiple currency pairs simultaneously.

Sometimes, an exception is thrown when parsing the results from the exchange; other times there is no error, but some trades contain very strange dates (e.g., extremely far into the past or future).

Looking at an example, I think the cause is in the `BittrexUtils` class:

```
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:601)
        at java.lang.Long.parseLong(Long.java:631)
        at java.text.DigitList.getLong(DigitList.java:195)
        at java.text.DecimalFormat.parse(DecimalFormat.java:2051)
        at java.text.SimpleDateFormat.subParse(SimpleDateFormat.java:2162)
        at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1514)
        at java.text.DateFormat.parse(DateFormat.java:364)
        at org.knowm.xchange.bittrex.v1.BittrexUtils.toDate(BittrexUtils.java:43)
        at org.knowm.xchange.bittrex.v1.BittrexAdapters.adaptTrade(BittrexAdapters.java:104)
        at org.knowm.xchange.bittrex.v1.BittrexAdapters.adaptTrades(BittrexAdapters.java:118)
        at org.knowm.xchange.bittrex.v1.service.BittrexMarketDataService.getTrades(BittrexMarketDataService.java:84)
```

It looks as though there's a static instance of `SimpleDateFormat` in `BittrexUtils`, which is not thread-safe.

**Comment by douggie** [comment]
HI Keith,

I have not checked the code, but I am using bittrex and many other xchange
Exchanges with multiple threads, this is the general model

1) Instantiate one instance of the xchange Exchange (i.e. singleton)
2) Have each tread sync on the given xchange exchange object whilst using
it (to keep things like nonces in sync)
3) release sync on the given xchange Exchange object.

You can take a look at an implementation here:

https://github.com/timolson/cointrader/blob/master/src/main/java/org/cryptocoinpartners/module/xchange/XchangeOrderService.java

Regards

Douggie

**Comment by keith-f** [comment]
Hi Douggie,

Thanks for your reply. I usually do synchronize threads while accessing an Exchange instance. However, in this particular case, I'm accessing public trade data only, so there are no nonces to sync or anything else that is dependent on thread ordering.

I raised this issue because I've been pulling public trade data in a multi-threaded fashion with a few other exchange implementations with no issue (specifically Poloniex, Kraken and GDAX). And I think that replacing the shared `SimpleDateFormat` instance mentioned above would fix the issue for the Bittrex implementation too.

However, I accept that there's an underlying assumption that *all* Exchange calls are synchronized. Maybe the safest option is to use multiple instances of `Exchange`.

Thanks,
Keith

**Comment by npomfret** [comment]
@keith-f i think is right, SimpleDateFormat shouldn't be shared. I can fix

**Comment by timmolter** [comment]
Yup, sounds familiar. I recently fixed a module that shared a formatter.

**Comment by npomfret** [comment]
The his be fixed.  Please close
