### ISSUE TITLE
JsonParseException on Poloniex

### ISSUE THREAD

**Issue by EzBar** [timmolter/XChange#1667]
Hi,

A few days ago I started getting the below warnings when polling Poloniex.
Any clue what's the root cause?

[Poller_SYS_BTC_Poloniex] WARN si.mazi.rescu.ResponseReader - Noncritical error parsing error output: <!DOCTYPE html><html lang="en"><head>	<title>Poloniex - Bitcoin/Cryptocurrency Exchange</title>...
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: <!DOCTYPE html><html lang="en">...; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1902)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:749)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3825)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3774)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2871)
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53)
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58)
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120)
	at com.sun.proxy.$Proxy16.getOrderBook(Unknown Source)
	at org.knowm.xchange.poloniex.service.PoloniexMarketDataServiceRaw.getPoloniexDepth(PoloniexMarketDataServiceRaw.java:108)
	at org.knowm.xchange.poloniex.service.PoloniexMarketDataService.getOrderBook(PoloniexMarketDataService.java:55)
	at nostro.infrastructure.MarketPoller.getOrderBook(MarketPoller.java:330)
	at nostro.infrastructure.MarketPoller.run(MarketPoller.java:418)
	at java.lang.Thread.run(Unknown Source)

**Comment by npomfret** [comment]
Poloniex was down for days recently.  I think maybe that's why.  There are rumours that isn't close to going bust.  Be warned!

**Comment by EzBar** [comment]
Wow.. thanks for the head-up mate.
This may have a major effect on the entire market. I sure hope these are merely rumors...

**Comment by npomfret** [comment]
They went down for 2 days and not a word of explanation to their customers.  And shortly before they changed their terms and conditions, inducing adding some clauses about not being able to sue them!  The rumour is they are insolvent.
