### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchFieldError: ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT

### ISSUE THREAD

**Issue by SilenceBTC** [timmolter/XChange#1742]
Hi,

Im trying  to run PoloniexMarketDataDemo from Eclipse and Im getting error.

Can You help mi please.

`Exception in thread "main" java.lang.NoSuchFieldError: ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT
	at org.knowm.xchange.poloniex.service.PoloniexBaseService$1.configureObjectMapper(PoloniexBaseService.java:43)
	at si.mazi.rescu.serialization.jackson.DefaultJacksonObjectMapperFactory.createObjectMapper(DefaultJacksonObjectMapperFactory.java:45)
	at si.mazi.rescu.RestInvocationHandler.<init>(RestInvocationHandler.java:75)
	at si.mazi.rescu.RestProxyFactory.createProxy(RestProxyFactory.java:47)
	at org.knowm.xchange.poloniex.service.PoloniexBaseService.<init>(PoloniexBaseService.java:53)
	at org.knowm.xchange.poloniex.service.PoloniexMarketDataServiceRaw.<init>(PoloniexMarketDataServiceRaw.java:28)
	at org.knowm.xchange.poloniex.service.PoloniexMarketDataService.<init>(PoloniexMarketDataService.java:30)
	at org.knowm.xchange.poloniex.PoloniexExchange.initServices(PoloniexExchange.java:29)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:106)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:99)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:148)
	at org.knowm.xchange.examples.poloniex.marketdata.PoloniexMarketDataDemo.main(PoloniexMarketDataDemo.java:27)`

**Comment by timmolter** [comment]
It works for me. Maybe their API was down? Or you need to use the latest SNAPSHOT code. 

<https://github.com/timmolter/XChange/wiki/Frequently-Asked-Questions#what-is-the-release-cycle-for-xchange>
