### ISSUE TITLE
date params for CexIOTradeServiceRaw.CexIOTradeHistoryParams not working

### ISSUE THREAD

**Issue by npomfret** [timmolter/XChange#1775]
I'm unable to get any **date** params working for trade history in for the cex.io exchange.  I think its a problem with their API but their support is pretty awful and won't answer my questions.

Has anyone managed to get this working?

**Comment by timmolter** [comment]
Any progress on this?

**Comment by npomfret** [comment]
Yes, that's fixed now.  The implementation didn't follow the spec and was using http header params instead of JSON in the body.  Amazingly it worked in most cases, but not for trade history.  It's been re-written now to follow the spec.

**Comment by stilltldr** [comment]
Hi,

how do you get the trade history? I still don't get it to work properly:

```java
public List<UserTrade> getTradeHistory() throws IOException {

        Exchange exchange = ExchangeFactory.INSTANCE.createExchange(mCexIOExSpec);
        TradeService ts = exchange.getTradeService();

        ArrayList<CurrencyPair> registeredCurrencyPairs = getRegisteredCurrencyPairs();

        ArrayList<UserTrade> returnValue = new ArrayList<>();

        for (CurrencyPair currencyPair : registeredCurrencyPairs) {
            UserTrades userTrades = ts.getTradeHistory(new CexIOTradeServiceRaw.CexIOTradeHistoryParams(currencyPair));
            if (userTrades == null){
                return returnValue;
            }

            List<UserTrade> userTradesList = userTrades.getUserTrades();

            if (userTradesList == null){
                return returnValue;
            }

            returnValue.addAll(userTradesList);
        }

        return returnValue;

    }
```
Returns:
```
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy20.archivedOrders(Unknown Source)
	at org.knowm.xchange.cexio.service.CexIOTradeServiceRaw.archivedOrders(CexIOTradeServiceRaw.java:154)
	at org.knowm.xchange.cexio.service.CexIOTradeService.getTradeHistory(CexIOTradeService.java:95)
[...]
Caused by: si.mazi.rescu.HttpStatusIOException: (was java.lang.NullPointerException) (through reference chain: java.util.ArrayList[0])
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120)
	... 57 more

```

**Comment by npomfret** [comment]
TradeHistoryParamsAll params = new TradeHistoryParamsAll();
                params.setCurrencyPair(currencyPair);
                params.setStartTime(startTime);
                params.setEndTime(endTime);
                params.setPageLength(500);

                UserTrades tradeHistory = exchangeApi.getTradeHistory(params);

**Comment by stilltldr** [comment]
Thank you @npomfret !
