### ISSUE TITLE
Bitfinex IllegalArgumentException error

### ISSUE THREAD

**Issue by Eldenayri** [timmolter/XChange#1791]
i am getting warn on bitstamptickerdemo and cexio tickerdemo. i need just ticker datas and there is an exception. i am newbee and need help for fix that exeption. i am sorry if stupid question. 

bitstamp exeption :  

11:08:06.843 [default] [main] DEBUG org.knowm.xchange.ExchangeFactory - Creating default exchange from class name 
11:08:06.843 [default] [main] DEBUG org.knowm.xchange.ExchangeFactory - Creating default exchange from class name 
11:08:07.085 [default] [main] WARN  o.k.x.bitstamp.BitstampExchange - An exception occured while loading the metadata file from the file system. This is just a warning and can be ignored, but it may lead to unexpected results, so it's better to address it. com.fasterxml.jackson.databind.JsonMappingException: No enum constant java.util.concurrent.TimeUnit.MİNUTES (through reference chain: org.knowm.xchange.dto.meta.ExchangeMetaData["private_rate_limits"]->Object[][0]->org.knowm.xchange.dto.meta.RateLimit["time_unit"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:379)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:339)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:513)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:396)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1194)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:196)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:20)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:396)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1194)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2899)
	at org.knowm.xchange.BaseExchange.loadMetaData(BaseExchange.java:137)
	at org.knowm.xchange.BaseExchange.loadExchangeMetaData(BaseExchange.java:128)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:96)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:98)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:147)
	at org.knowm.xchange.examples.bitstamp.marketdata.BitstampTickerDemo.main(BitstampTickerDemo.java:22)
Caused by: java.lang.IllegalArgumentException: No enum constant java.util.concurrent.TimeUnit.MİNUTES
	at java.lang.Enum.valueOf(Unknown Source)
	at java.util.concurrent.TimeUnit.valueOf(Unknown Source)
	at org.knowm.xchange.dto.meta.RateLimit$TimeUnitDeserializer.deserialize(RateLimit.java:61)
	at org.knowm.xchange.dto.meta.RateLimit$TimeUnitDeserializer.deserialize(RateLimit.java:1)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
	... 20 common frames omitted

11:08:07.138 [default] [main] INFO  o.k.x.bitstamp.BitstampExchange - Calling Remote Init... 
11:08:07.138 [default] [main] INFO  o.k.x.bitstamp.BitstampExchange - No remote initialization implemented for Bitstamp. The exchange meta data for this exchange is loaded from a json file containing hard-coded exchange meta-data. This may or may not be OK for you, and you should understand exactly how this works. Each exchange can either 1) rely on the hard-coded json file that comes packaged with XChange's jar, 2) provide your own override json file, 3) properly implement the `remoteInit()` method for the exchange (please submit a pull request so the whole community can benefit) or 4) a combination of hard-coded JSON and remote API calls. For more info see: https://github.com/timmolter/XChange/wiki/Design-Notes#exchange-metadata 
BitstampTicker [last=4290.00, high=4453.00, low=4258.60, vwap=4371.29, volume=9917.38719499, bid=4290.00, ask=4293.31, timestamp=1507018081]

**Comment by Optictrollz** [comment]
got this too 
14:54:09.492 [default] [main] DEBUG org.knowm.xchange.ExchangeFactory - Creating default exchange from class name 
14:54:09.495 [default] [main] DEBUG org.knowm.xchange.ExchangeFactory - Creating default exchange from class name 
14:54:09.668 [default] [main] DEBUG o.k.x.bitstamp.BitstampExchange - ExchangeMetaData [currencyPairs={BTC/USD=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=0.010000000, maximumAmount=null, priceScale=2], BTC/EUR=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=0.010000000, maximumAmount=null, priceScale=2], EUR/USD=CurrencyPairMetaData [tradingFee=0.0020, minimumAmount=5.000000000, maximumAmount=null, priceScale=2], XRP/USD=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=200.0000000, maximumAmount=null, priceScale=5], XRP/EUR=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=200.0000000, maximumAmount=null, priceScale=5], XRP/BTC=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=200.0000000, maximumAmount=null, priceScale=8], LTC/USD=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=0.15, maximumAmount=null, priceScale=2], LTC/EUR=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=0.15, maximumAmount=null, priceScale=2], LTC/BTC=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=0.15, maximumAmount=null, priceScale=8], ETH/EUR=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=5, maximumAmount=null, priceScale=2], ETH/USD=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=5, maximumAmount=null, priceScale=2], ETH/BTC=CurrencyPairMetaData [tradingFee=0.0025, minimumAmount=5, maximumAmount=null, priceScale=8]}, currencies={BTC=CurrencyMetaData{scale=8}, USD=CurrencyMetaData{scale=2}, EUR=CurrencyMetaData{scale=2}, XRP=CurrencyMetaData{scale=8}, LTC=CurrencyMetaData{scale=8}, ETH=CurrencyMetaData{scale=8}}, publicRateLimits=null, privateRateLimits=[RateLimit [calls=60, timeSpan=0, timeUnit=MINUTES]], shareRateLimits=true] 
14:54:09.699 [default] [main] INFO  o.k.x.bitstamp.BitstampExchange - Calling Remote Init... 
14:54:09.699 [default] [main] INFO  o.k.x.bitstamp.BitstampExchange - No remote initialization implemented for Bitstamp. The exchange meta data for this exchange is loaded from a json file containing hard-coded exchange meta-data. This may or may not be OK for you, and you should understand exactly how this works. Each exchange can either 1) rely on the hard-coded json file that comes packaged with XChange's jar, 2) provide your own override json file, 3) properly implement the `remoteInit()` method for the exchange (please submit a pull request so the whole community can benefit) or 4) a combination of hard-coded JSON and remote API calls. For more info see: https://github.com/timmolter/XChange/wiki/Design-Notes#exchange-metadata 
fetching data...
received data.
plotting...
Exception in thread "main" java.lang.IllegalArgumentException: Y-Axis data cannot be empty!!! >asks
	at org.knowm.xchart.XYChart.sanityCheck(XYChart.java:315)
	at org.knowm.xchart.XYChart.addSeries(XYChart.java:236)
	at org.knowm.xchart.XYChart.addSeries(XYChart.java:104)
	at org.knowm.xchange.examples.bitstamp.marketdata.DepthChartDemo.main(DepthChartDemo.java:82)

**Comment by timmolter** [comment]
@Optictrollz I fixed it. Pull latest commit on develop branch.
@Eldenayri Try the latest release. It works for me.
