### ISSUE TITLE
Invalid moment parameter encountered in bitbay placelimitorder

### ISSUE THREAD

**Issue by Leungfranklin** [timmolter/XChange#1792]
When I call bitbay placelimitorder, the following error is encountered
Exception in thread "main" org.knowm.xchange.exceptions.ExchangeException: 503: Invalid moment parameter. Request time doesn't match current server time
	at org.knowm.xchange.bitbay.service.BitbayBaseService.checkError(BitbayBaseService.java:37)
	at org.knowm.xchange.bitbay.service.BitbayTradeServiceRaw.placeBitbayOrder(BitbayTradeServiceRaw.java:36)
	at org.knowm.xchange.bitbay.service.BitbayTradeService.placeLimitOrder(BitbayTradeService.java:60)
	at org.knowm.xchange.trading.BitbayTickerDemo.main(BitbayTickerDemo.java:63)

**Comment by timmolter** [comment]
Try creating a new API key on their site and using that in XChange. Otherwise, I'm not sure what to try.

**Comment by Leungfranklin** [comment]
Turns out that my PC time sync with NTP server has not been started. Bitbay check the time against their own time and rejects if there is a significant time difference. After time sync my PC, it works fine. Thanks.
