### ISSUE TITLE
Independent Reserve issue

### ISSUE THREAD

**Issue by Swoorup** [timmolter/XChange#1900]
When running the marketdata/DepthDemo I get the following exception.

Any ideas?

```
10:15:12.198 [default] [main] DEBUG org.knowm.xchange.ExchangeFactory - Creating default exchange from class name 
10:15:12.202 [default] [main] DEBUG org.knowm.xchange.ExchangeFactory - Creating default exchange from class name 
10:15:12.535 [default] [main] DEBUG o.k.x.i.IndependentReserveExchange - ExchangeMetaData [currencyPairs={BTC/USD=CurrencyPairMetaData [tradingFee=null, minimumAmount=null, maximumAmount=null, priceScale=2], BTC/AUD=CurrencyPairMetaData [tradingFee=null, minimumAmount=null, maximumAmount=null, priceScale=2], BTC/NZD=CurrencyPairMetaData [tradingFee=null, minimumAmount=null, maximumAmount=null, priceScale=2], ETH/USD=CurrencyPairMetaData [tradingFee=null, minimumAmount=null, maximumAmount=null, priceScale=2], ETH/AUD=CurrencyPairMetaData [tradingFee=null, minimumAmount=null, maximumAmount=null, priceScale=2], ETH/NZD=CurrencyPairMetaData [tradingFee=null, minimumAmount=null, maximumAmount=null, priceScale=2]}, currencies={}, publicRateLimits=null, privateRateLimits=[RateLimit [calls=60, timeSpan=0, timeUnit=MINUTES]], shareRateLimits=true] 
10:15:12.783 [default] [main] INFO  o.k.x.i.IndependentReserveExchange - Calling Remote Init... 
10:15:12.783 [default] [main] INFO  o.k.x.i.IndependentReserveExchange - No remote initialization implemented for IndependentReserve. The exchange meta data for this exchange is loaded from a json file containing hard-coded exchange meta-data. This may or may not be OK for you, and you should understand exactly how this works. Each exchange can either 1) rely on the hard-coded json file that comes packaged with XChange's jar, 2) provide your own override json file, 3) properly implement the `remoteInit()` method for the exchange (please submit a pull request so the whole community can benefit) or 4) a combination of hard-coded JSON and remote API calls. For more info see: https://github.com/timmolter/XChange/wiki/Design-Notes#exchange-metadata 
Exception in thread "main" si.mazi.rescu.HttpStatusIOException: Cannot construct instance of `org.knowm.xchange.independentreserve.dto.marketdata.IndependentReserveOrderBook`, problem: javax/xml/bind/DatatypeConverter
 at [Source: (String)"{"BuyOrders":[{"OrderType":"LimitBid","Price":8300.0,"Volume":1.00000000},{"OrderType":"LimitBid","Price":8200.0,"Volume":1.00000000},{"OrderType":"LimitBid","Price":8122.96,"Volume":0.01964843},{"OrderType":"LimitBid","Price":8120.0,"Volume":1.00000000},{"OrderType":"LimitBid","Price":8112.0,"Volume":3.24832191},{"OrderType":"LimitBid","Price":8100.04,"Volume":0.62300000},{"OrderType":"LimitBid","Price":8088.67,"Volume":0.02000000},{"OrderType":"LimitBid","Price":8057.25,"Volume":0.9631015},{"O"[truncated 29592 chars]; line: 1, column: 30092]
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120)
	at com.sun.proxy.$Proxy10.getOrderBook(Unknown Source)
	at org.knowm.xchange.independentreserve.service.IndependentReserveMarketDataServiceRaw.getIndependentReserveOrderBook(IndependentReserveMarketDataServiceRaw.java:30)
	at org.knowm.xchange.independentreserve.service.IndependentReserveMarketDataService.getOrderBook(IndependentReserveMarketDataService.java:34)
	at org.knowm.xchange.examples.independentreserve.marketdata.DepthDemo.generic(DepthDemo.java:35)
	at org.knowm.xchange.examples.independentreserve.marketdata.DepthDemo.main(DepthDemo.java:27)

Process finished with exit code 1
```

**Comment by timmolter** [comment]
My guess is that Independent Reserve changed their response JSON and the XChange code not is broken. <See: https://github.com/timmolter/XChange/wiki/New-Implementation-Best-Practices>

**Comment by Swoorup** [comment]
This can be closed. I can only find this issue on JDK9, no issues on JDK8
