### ISSUE TITLE
YoBitExchange.class init error

### ISSUE THREAD

**Issue by mike789vvv** [timmolter/XChange#1907]
Hi)
Found an bug,  when yobit exchange class init

ExchangeSpecification exSpec = new ExchangeSpecification(YoBitExchange.class);
exSpec.setApiKey("KEY_TOKEN_ID");
exSpec.setSecretKey("KEY_USER_SECRET");
Exchange yoBitExchange = ExchangeFactory.INSTANCE.createExchange(exSpec);

Exception in thread "main" java.lang.NullPointerException
	at org.knowm.xchange.yobit.YoBitAdapters.adaptToExchangeMetaData(YoBitAdapters.java:76)
	at org.knowm.xchange.yobit.YoBitExchange.remoteInit(YoBitExchange.java:47)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:111)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:168)
	at rutrade.bot.exchanges.yobit.YoBitBookDemo.main(YoBitBookDemo.java:24)

**Comment by lucarosellini** [comment]
I confirm this bug in the develop branch, master is fine.

It's actually raising a NPE when initialising currency pair DKC/WAVES. 
At YoBitAdapters, line 76, `exchangeMetaData.getCurrencies().get(pair.counter)` is null.

The failing code has been merged with PR #1877

**Comment by mike789vvv** [comment]
its working ok) thanks)
