### ISSUE TITLE
ArithmeticException thrown when initializing exchange

### ISSUE THREAD

**Issue by KosherBacon** [timmolter/XChange#1936]
```java
Caused by: java.lang.ArithmeticException: Rounding necessary
	at java.math.BigDecimal.commonNeedIncrement(BigDecimal.java:4148)
	at java.math.BigDecimal.needIncrement(BigDecimal.java:4204)
	at java.math.BigDecimal.divideAndRound(BigDecimal.java:4112)
	at java.math.BigDecimal.setScale(BigDecimal.java:2452)
	at org.knowm.xchange.gdax.GDAXAdapters.adaptToExchangeMetaData(GDAXAdapters.java:221)
	at org.knowm.xchange.gdax.GDAXExchange.remoteInit(GDAXExchange.java:50)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:111)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:168)
```

Unable to use GDAX exchange. The error appears during the initialization of the BigDecimals in `adaptToExchangeMetaData` within [`GDAXAdapters.class`](https://github.com/timmolter/XChange/blob/c88ebbca5a65b86e6e6ff88ef1a44937b6d74217/xchange-gdax/src/main/java/org/knowm/xchange/gdax/GDAXAdapters.java#L221)

Consider changing the rounding mode from `BigDecimal.ROUND_UNNECESSARY`?

I'm using xchange version 4.3.0 from Maven.

**Comment by iddqd1** [comment]
The same here.

**Comment by timmolter** [comment]
I'm working on a fix now...

**Comment by iddqd1** [comment]
@timmolter 
int minScale = product.getBaseMinSize().scale() > product.getQuoteIncrement().scale() ? product.getBaseMinSize().scale():product.getQuoteIncrement().scale();

**Comment by npomfret** [comment]
The problem is that there is a product (ETH-EUR) with a minimum amount is 0.001 which is being rounded to 2dp.  Obviously, this doesn't really make any sense.

**Comment by timmolter** [comment]
done. please let me know if there are still issues.
