### ISSUE TITLE
Kraken Order results in [EGeneral:Invalid arguments]

### ISSUE THREAD

**Issue by razem-io** [timmolter/XChange#1954]
Hello,

I am trying to trade using the api since the web interface of kraken is not usable anymore.

When I set a Limit Order or Market Order I get the following exception:

```
org.knowm.xchange.exceptions.ExchangeException: [EGeneral:Invalid arguments]
	at org.knowm.xchange.kraken.service.KrakenBaseService.checkResult(KrakenBaseService.java:74)
	at org.knowm.xchange.kraken.service.KrakenTradeServiceRaw.placeKrakenOrder(KrakenTradeServiceRaw.java:167)
	at org.knowm.xchange.kraken.service.KrakenTradeServiceRaw.placeKrakenLimitOrder(KrakenTradeServiceRaw.java:145)
	at services.ExchangeService.$anonfun$buy$1(ExchangeService.scala:92)
	at scala.util.Try$.apply(Try.scala:209)
	at helpers.Rich$.retry(Rich.scala:8)
	at services.ExchangeService.buy(ExchangeService.scala:89)
	at controllers.Application.$anonfun$limitBuy$3(Application.scala:25)
	at controllers.Application.$anonfun$limitBuy$3$adapted(Application.scala:20)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
```

I am using the following code (scala):

``` 
val limitOrder = new LimitOrder(OrderType.BID, amount.bigDecimal, currencyPair, null, null, limitPrice.bigDecimal)

retry(5) {
  Logger.info(s"Trying to place order -> amount $amount, limit $limitPrice, pair $currencyPair, account ${account.accountName}")
  //account.exchange.getTradeService.placeLimitOrder(limitOrder)
       
  account.exchange.getTradeService.asInstanceOf[KrakenTradeServiceRaw].placeKrakenLimitOrder(limitOrder).toString
}
```

I am not sure yet what causes the error. Everything else seems to work fine (ticker, account).

**Comment by razem-io** [comment]
Okay I debugged for an hour. I think I found the problem:

```
String result = KrakenUtils.createKrakenCurrencyPair(CurrencyPair.BTC_EUR)
```

`result == null` in this case

**Comment by razem-io** [comment]
Sorry. I already used version 4.3.1 but forgot to resync sbt when using intellij. So it still used 4.3.0 which had this bug. Closed.
