### ISSUE TITLE
YoBitExchange throws NullPointerException on creation

### ISSUE THREAD

**Issue by cowwoc** [timmolter/XChange#2040]
Version 4.3.1

This issue could be related to https://github.com/timmolter/XChange/issues/1907 although the stack-trace is different.

`ExchangeFactory.createExchange(YoBitExchange.class)` throws:

```
Exception in thread "main" java.lang.IllegalStateException: cannot create digest
	at org.knowm.xchange.yobit.YoBitDigest.createInstance(YoBitDigest.java:24)
	at org.knowm.xchange.yobit.service.YoBitBaseService.<init>(YoBitBaseService.java:18)
	at org.knowm.xchange.yobit.service.YoBitMarketDataServiceRaw.<init>(YoBitMarketDataServiceRaw.java:17)
	at org.knowm.xchange.yobit.service.YoBitMarketDataService.<init>(YoBitMarketDataService.java:38)
	at org.knowm.xchange.yobit.YoBitExchange.initServices(YoBitExchange.java:39)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:106)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:98)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:147)
Caused by: java.lang.NullPointerException
	at org.knowm.xchange.service.BaseParamsDigest.<init>(BaseParamsDigest.java:33)
	at org.knowm.xchange.yobit.YoBitDigest.<init>(YoBitDigest.java:17)
	at org.knowm.xchange.yobit.YoBitDigest.createInstance(YoBitDigest.java:22)
	... 9 more
```

**Comment by CoreyNelson** [comment]
I'm new to using XChange and I've hit this bug. I'd love to be able to use XChange to connect to YoBit. Yobit definitely allows public market data: https://yobit.net/en/api/

I might try to fix this. @timmolter , any advice for me? It there a particularly well implemented exchange I should reference?

**Comment by timmolter** [comment]
I'd only suggest reading this: https://github.com/knowm/XChange/wiki/New-Implementation-Best-Practices

All modules have been more of less implemented in the same way.

**Comment by DjihadBengati** [comment]
Hi all ! 
Any news about this issue ? :)

**Comment by DjihadBengati** [comment]
Pull request done for this issue :) https://github.com/knowm/XChange/pull/2885
