### ISSUE TITLE
Frequent connection reset errors from Poloniex

### ISSUE THREAD

**Issue by cowwoc** [timmolter/XChange#2042]
Version 4.3.1

I am getting frequent "connection reset" errors at initialization time:

```
Exception in thread "main" org.knowm.xchange.exceptions.ExchangeException: java.net.SocketException: Connection reset
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:113)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:98)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:147)
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:425)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:154)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1031)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at java.base/sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1402)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1429)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329)
	at si.mazi.rescu.HttpTemplate.receive(HttpTemplate.java:121)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:156)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120)
	at com.sun.proxy.$Proxy13.getCurrencyInfo(Unknown Source)
	at org.knowm.xchange.poloniex.service.PoloniexMarketDataServiceRaw.getPoloniexCurrencyInfo(PoloniexMarketDataServiceRaw.java:36)
	at org.knowm.xchange.poloniex.PoloniexExchange.remoteInit(PoloniexExchange.java:58)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:111)
	... 4 more
```

Is this a rate-limiting thing on their end? Instability? Or some sort of bug in this library? Would it make sense to add a retry loop here?

**Comment by timmolter** [comment]
It's tough to say. It seems like a network issue to me but they could have also changed something on their API, and Xchange hasn't yet been updated.
