### ISSUE TITLE
Binance account info throws ZipException: Not in GZIP format

### ISSUE THREAD

**Issue by suchac** [timmolter/XChange#2060]
```
java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165) ~[na:1.8.0_151]
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79) ~[na:1.8.0_151]
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91) ~[na:1.8.0_151]
	at si.mazi.rescu.HttpTemplate.readInputStreamAsEncodedString(HttpTemplate.java:217) ~[rescu-2.0.1.jar:na]
	at si.mazi.rescu.HttpTemplate.receive(HttpTemplate.java:126) ~[rescu-2.0.1.jar:na]
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:156) ~[rescu-2.0.1.jar:na]
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120) ~[rescu-2.0.1.jar:na]
	at com.sun.proxy.$Proxy75.account(Unknown Source) ~[na:na]
	at org.knowm.xchange.binance.service.BinanceAccountServiceRaw.account(BinanceAccountServiceRaw.java:25) ~[xchange-binance-4.3.2-20171228.140010-55.jar:na]
	at org.knowm.xchange.binance.service.BinanceAccountService.getAccountInfo(BinanceAccountService.java:41) ~[xchange-binance-4.3.2-20171228.140010-55.jar:na]
```

**Comment by KevinJannis** [comment]
I am receiving the same issue.
Is there any way to disable gzip for rescu?

(Wanted to create a similar issue, but better to comment here I think..)

**Comment by ww3456** [comment]
I think it was an temporary issue on the Binance side. My application received similar ZipExceptions between 13:44 and 16:19 GMT which have now resolved without any changes for me. 

Not sure if it is related, but since this morning the performance of the authenticated user trade history has also worsened, I had to increase the socket timeout to >5 seconds in order to get any data back.

**Comment by KevinJannis** [comment]
The issues are also resolved on my machine at this moment.

On 28 Dec 2017 6:11 pm, ww3456 <notifications@github.com> wrote:

I think it was an temporary issue on the Binance side. My application received similar ZipExceptions between 13:44 and 16:19 GMT which have now resolved without any changes for me.

Not sure if it is related, but since this morning the performance of the authenticated user trade history has also worsened, I had to increase the socket timeout to >5 seconds in order to get any data back.
