### ISSUE TITLE
HitBTC: Not supported HitBTC symbol: XRPUSDT

### ISSUE THREAD

**Issue by solovieff** [timmolter/XChange#2126]
Seems, that should be added to HitbtcAdapters

Exception:
```
java.lang.RuntimeException: Not supported HitBTC symbol: XRPUSDT
	at org.knowm.xchange.hitbtc.v2.HitbtcAdapters.lambda$adaptSymbol$1(HitbtcAdapters.java:49)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.knowm.xchange.hitbtc.v2.HitbtcAdapters.adaptSymbol(HitbtcAdapters.java:49)
	at org.knowm.xchange.hitbtc.v2.HitbtcAdapters.adaptTradeHistory(HitbtcAdapters.java:174)
	at org.knowm.xchange.hitbtc.v2.service.HitbtcTradeService.getTradeHistory(HitbtcTradeService.java:96)

```

Code:
```
TradeHistoryParams params = tradeService.createTradeHistoryParams();

        List<UserTrade> allTrades = new LinkedList<>();

        if (params instanceof TradeHistoryParamCurrencyPair) {
            TradeHistoryParamCurrencyPair paramCurrencyPair = (TradeHistoryParamCurrencyPair) params;
            //paramCurrencyPair.setCurrencyPair(CurrencyPair.BTC_XRP);
            //allTrades = CryptoUtils.getCurrentTradesHistoryForCurrencies(new HashSet<>(), tradeService, paramCurrencyPair);
            UserTrades userTradesEntity = tradeService.getTradeHistory(paramCurrencyPair);
            allTrades = userTradesEntity.getUserTrades();
        } else {
            UserTrades userTradesEntity = tradeService.getTradeHistory(params);
            allTrades = userTradesEntity.getUserTrades();
        }
```

**Comment by solovieff** [comment]
4.3.2
