### ISSUE TITLE
[BITTREX] si.mazi.rescu.HttpStatusIOException: N/A

### ISSUE THREAD

**Issue by lucarosellini** [timmolter/XChange#2161]
Hi everyone, 
I am quite often getting the following error while calling BittrexTradeService.getOrder using the ID of  a recently opened order:

```
si.mazi.rescu.HttpStatusIOException: N/A
 at [Source: {"success":true,"message":"","result":{"AccountId":null,"OrderUuid":"1642ee42-68b2-4a1d-8fb3-0a4eb5e574bf","Exchange":"USDT-BTC","Type":"LIMIT_SELL","Quantity":0.01561523,"QuantityRemaining":0.01561523,"Limit":13465.99999994,"Reserved":0.01561523,"ReserveRemaining":0.01561523,"CommissionReserved":0.00000000,"CommissionReserveRemaining":0.00000000,"CommissionPaid":0.00000000,"Price":0.00000000,"PricePerUnit":null,"Opened":"2018-01-15T03:09:42.7","Closed":null,"IsOpen":true,"Sentinel":"84a91b41-1127-41db-9fa2-c3251098ec9d","CancelInitiated":false,"ImmediateOrCancel":false,"IsConditional":false,"Condition":"NONE","ConditionTarget":null}}; line: 1, column: 459] (through reference chain: org.knowm.xchange.bittrex.dto.account.BittrexOrderResponse["result"]->org.knowm.xchange.bittrex.dto.account.BittrexOrder["Closed"])
        at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
        at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
        at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)
        at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120)
        at com.sun.proxy.$Proxy21.getOrder(Unknown Source)
        at org.knowm.xchange.bittrex.service.BittrexTradeServiceRaw.getBittrexOrder(BittrexTradeServiceRaw.java:138)
        at org.knowm.xchange.bittrex.service.BittrexTradeService.getOrder(BittrexTradeService.java:111)
```

If I understand correctly, the above error basically means mazi was not able to deserialize the json coming from the exchange. Could this be caused by the null value for the "Closed" property?

Thanks in advance,
Luca

**Comment by timmolter** [comment]
I think your assessment is correct.

**Comment by lucarosellini** [comment]
I'll do some more tests but it seems the change on `BittrexUtils.toDate` in PR #2159 merged today also fixes this problem.

**Comment by lucarosellini** [comment]
PR #2159 definitely solves the issue.
