### ISSUE TITLE
[BITSTAMP] Can not deserialize value of type int from String "None": not a valid Integer value

### ISSUE THREAD

**Issue by oliverrenner** [timmolter/XChange#2163]
i bought eth via credit card on bitstamp, it seems the api cant parse that response:

error: Can not deserialize value of type int from String "None": not a valid Integer value

```
 at [Source: java.io.StringReader@19d5465; line: 1, column: 2410] (through reference chain: java.lang.Object[][13]->org.knowm.xchange.bitstamp.dto.tra
<img width="694" alt="bildschirmfoto 2018-01-15 um 12 29 02" src="https://user-images.githubusercontent.com/7191924/34940410-b9dfc442-f9ef-11e7-8868-6c76aa3d2e61.png">
de.BitstampUserTransaction["type"])
2018-01-15 12:13:49.055  [] WARN 6394 --- [pool-2-thread-1] si.mazi.rescu.ResponseReader             : Noncritical error parsing error output: [{"fee": "0.00000000", "btc_usd": "0.00", "datetime": "2018-01-15 10:35:28", "usd": 0.0, "btc": "-0.00716216", "type": "1", "id": 45707166, "eur": 0.0}, {"fee": "0.10", "order_id": 769217533, "datetim...

com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of org.knowm.xchange.bitstamp.dto.BitstampException out of START_ARRAY token
 at [Source: java.io.StringReader@65ea1e92; line: 1, column: 1]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270) ~[jackson-databind-2.8.7.jar!/:2.8.7]
        at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234) ~[jackson-databind-2.8.7.jar!/:2.8.7]
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122) ~[jackson-databind-2.8.7.jar!/:2.8.7]
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1075) ~[jackson-databind-2.8.7.jar!/:2.8.7]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromArray(BeanDeserializerBase.java:1378) ~[jackson-databind-2.8.7.jar!/:2.8.7]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:174) ~[jackson-databind-2.8.7.jar!/:2.8.7]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150) ~[jackson-databind-2.8.7.jar!/:2.8.7]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798) ~[jackson-databind-2.8.7.jar!/:2.8.7]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2880) ~[jackson-databind-2.8.7.jar!/:2.8.7]
        at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53) ~[rescu-2.0.1.jar!/:na]
        at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58) ~[rescu-2.0.1.jar!/:na]
        at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82) ~[rescu-2.0.1.jar!/:na]
        at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169) [rescu-2.0.1.jar!/:na]
        at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157) [rescu-2.0.1.jar!/:na]
        at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120) [rescu-2.0.1.jar!/:na]
        at com.sun.proxy.$Proxy103.getUserTransactions(Unknown Source) [na:na]
        at org.knowm.xchange.bitstamp.service.BitstampAccountServiceRaw.getBitstampUserTransactions(BitstampAccountServiceRaw.java:167) [xchange-bitstamp-4.3.2.jar!/:na]
        at org.knowm.xchange.bitstamp.service.BitstampAccountService.getFundingHistory(BitstampAccountService.java:149) [xchange-bitstamp-4.3.2.jar!/:na]
        at com.cryptomargin.backend.balance.BalanceService.lambda$cacheCompletedFundingRecords$8(BalanceService.java:105) [classes!/:0.1-SNAPSHOT]
        at com.cryptomargin.backend.utils.RetryService.retry(RetryService.java:23) ~[classes!/:0.1-SNAPSHOT]
        at com.cryptomargin.backend.utils.RetryService.retry(RetryService.java:13) ~[classes!/:0.1-SNAPSHOT]
        at com.cryptomargin.backend.utils.RetryService$$FastClassBySpringCGLIB$$667abef6.invoke(<generated>) ~[classes!/:0.1-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) ~[spring-tx-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at com.cryptomargin.backend.utils.RetryService$$EnhancerBySpringCGLIB$$d9eec78e.retry(<generated>) ~[classes!/:0.1-SNAPSHOT]
        at com.cryptomargin.backend.balance.BalanceService.cacheCompletedFundingRecords(BalanceService.java:105) [classes!/:0.1-SNAPSHOT]
        at com.cryptomargin.backend.balance.BalanceService$$FastClassBySpringCGLIB$$a368d577.invoke(<generated>) ~[classes!/:0.1-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) ~[spring-tx-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at com.cryptomargin.backend.balance.BalanceService$$EnhancerBySpringCGLIB$$5496a3b1.cacheCompletedFundingRecords(<generated>) ~[classes!/:0.1-SNAPSHOT]
        at com.cryptomargin.backend.balance.BalanceHistoryTask.fetchSpecificHistory(BalanceHistoryTask.java:66) ~[classes!/:0.1-SNAPSHOT]
        at com.cryptomargin.backend.balance.BalanceHistoryTask.fetchHistory(BalanceHistoryTask.java:42) ~[classes!/:0.1-SNAPSHOT]
        at com.cryptomargin.backend.balance.BalanceHistoryTask$$FastClassBySpringCGLIB$$f79701fb.invoke(<generated>) ~[classes!/:0.1-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) ~[spring-tx-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at com.cryptomargin.backend.balance.BalanceHistoryTask$$EnhancerBySpringCGLIB$$358f1bbd.fetchHistory(<generated>) ~[classes!/:0.1-SNAPSHOT]
        at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_141]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_141]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_141]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_141]
```

**Comment by sdepold** [comment]
It seems that the "type" of a transaction is `"None"` if the transaction was a "Crypto currency purchase".

**Comment by sdepold** [comment]
I opened a support ticket at Bitstamp and asked for clarification. A temporary fix could be to treat this case as if it was a trade.

**Comment by oliverrenner** [comment]
Considering the response time of bitstamp I would appreciate the latter.

**Comment by sdepold** [comment]
:D

**Comment by sdepold** [comment]
If I can figure out how to run the tests, I might be able to open a PR 😊

**Comment by sdepold** [comment]
Hm… I don't get it. I change the tests, so that they should for sure fail buuuuuuut they don't :)

**Comment by oliverrenner** [comment]
is there something i could do locally ? this issue is a huge issue for me =)

**Comment by timmolter** [comment]
I run the tests in my IDE, Eclipse or IntelliJ. Otherwise `mvn clean test`.
