### ISSUE TITLE
Problem in extending the features of bitflyer sdk.

### ISSUE THREAD

**Issue by dovelive** [timmolter/XChange#2215]
Hi. @theo1985 
I have a question on using Bitflyer sdk.
I wanted to place a parent order for Bitflyer.
https://lightning.bitflyer.jp/docs?lang=en#submit-new-parent-order-special-order

So I added the function to Bitflyer.java like below.
```
  @POST
  @Path("me/sendparentorder")
  BitflyerParentOrderResponse placeParentOrder(@HeaderParam(ACCESS_KEY) String apiKey,
      @HeaderParam(ACCESS_TIMESTAMP) SynchronizedValueFactory<Long> nonce,
      @HeaderParam(ACCESS_SIGN) ParamsDigest paramsDigest,
      @FormParam("order_method") String ordeMethod,
      @FormParam("minute_to_expire") Integer minuteToExpire,
      @FormParam("time_in_force") String timeInForce,
      @FormParam("parameters") List<BitflyerParentOrderParameter> paramRequest
      ) throws IOException, BitflyerException;
```

And BitflyerParentOrderParameter.java is like this

```
...
  @JsonProperty("product_code")
  private String productCode;
  @JsonProperty("condition_type")
  private String conditionType;
  @JsonProperty("side")
  private String side;
  @JsonProperty("price")
  private BigDecimal price;
  @JsonProperty("size")
  private BigDecimal size;
  @JsonProperty("trigger_price")
  private BigDecimal triggerPrice;
  @JsonProperty("offset")
  private BigDecimal offset;
  public BitflyerParentOrderParameter(String productCode, String conditionType, String side, BigDecimal price, BigDecimal triggerPrice, BigDecimal size) {
      this.productCode = productCode;
      this.conditionType = conditionType;
      this.side = side;
      this.price = price;
      this.triggerPrice = triggerPrice;
      this.size = size;
  }
  ....
```

I made the place parent order function on BitflyerTradeServiceRaw.java like this

```
    public BitflyerParentOrderResponse placeParentOrder(String orderMethod, Integer minuteToExpire, String timeInForce, List<BitflyerParentOrderParameter> paramRequest) throws IOException {
        try {
            return bitflyer.placeParentOrder(apiKey, exchange.getNonceFactory(), signatureCreator, orderMethod, minuteToExpire, timeInForce, paramRequest);
        } catch (BitflyerException e) {
            throw handleError(e);
        }
    }
```

Finally I called that function on test function

```
        List<BitflyerParentOrderParameter> orderParam = new ArrayList<BitflyerParentOrderParameter>();
        orderParam.add(new BitflyerParentOrderParameter("BTC_JPY", "LIMIT", "BUY", BigDecimal.valueOf(1300000), null, BigDecimal.valueOf(0.1)));
        orderParam.add(new BitflyerParentOrderParameter("BTC_JPY", "LIMIT", "SELL", BigDecimal.valueOf(1320000), null, BigDecimal.valueOf(0.1)));
        orderParam.add(new BitflyerParentOrderParameter("BTC_JPY", "STOP_LIMIT", "SELL", BigDecimal.valueOf(1288000), BigDecimal.valueOf(1290000), BigDecimal.valueOf(0.1)));
        BitflyerParentOrderResponse marketOrderReturn = tradeServiceRaw.placeParentOrder("IFDOCO", 10000, "GTC", orderParam);
        System.out.println("Market Order return value: " + marketOrderReturn);
```

However the result showed me that there were no enough parameters.

```
Exception in thread "main" org.knowm.xchange.exceptions.ExchangeException: org.knowm.xchange.bitflyer.dto.BitflyerException: Not enough parameters.
	at org.knowm.xchange.bitflyer.service.BitflyerBaseService.handleError(BitflyerBaseService.java:45)
	at org.knowm.xchange.bitflyer.service.BitflyerTradeServiceRaw.placeParentOrder(BitflyerTradeServiceRaw.java:168)
	at bitcoinapi.BitflyerTest.main(BitflyerTest.java:142)
Caused by: org.knowm.xchange.bitflyer.dto.BitflyerException: Not enough parameters.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
```

I think that I have made the program according to the specification of bitflyer.
However I can't find the reason of errors.
I think there should be mistake creating the placing parent order function on Bitflyer.java, but I don't know how to fix it.
So would you like to help me fix this errors?
Regards.

**Comment by theo1985** [comment]
I suspect your missing your encapsulation in BitflyerParentOrderParameter.java, and as such the private members are omitted:

```
public String getProductCode() {
        return productCode;
    }

    public String getConditionType() {
        return conditionType;
    }

    public String getSide() {
        return side;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public BigDecimal getSize() {
        return size;
    }

    public BigDecimal getTriggerPrice() {
        return triggerPrice;
    }

    public BigDecimal getOffset() {
        return offset;
    }

    @Override
    public String toString() {
        return "BitflyerParentOrderParameter{" +
                "productCode=" + productCode +
                ", conditionType='" + conditionType + '\'' +
                ", side=" + side +
                ", price=" + price +
                ", size='" + size + '\'' +
                ", triggerPrice='" + triggerPrice + '\'' +
                ", offset='" + offset + '\'' +
                '}';
    }
```

**Comment by dovelive** [comment]
Thank you for replying @theo1985 
I am sorry but there are encapsulation methods on my code.
Though I hadn't write it on this post.
I think the there should be error on other side.
e.g. Definition of placeParentOrder function in Bitflyer.java
However I couldn't find it.

**Comment by theo1985** [comment]
The problem lies in Bitflyer.java:

 ```
 @POST
  @Path("me/sendparentorder")
  BitflyerParentOrderResponse placeParentOrder(@HeaderParam(ACCESS_KEY) String apiKey,
      @HeaderParam(ACCESS_TIMESTAMP) SynchronizedValueFactory<Long> nonce,
      @HeaderParam(ACCESS_SIGN) ParamsDigest paramsDigest,
      BitFlyerParentOrderRequest request) throws IOException, BitflyerException;
```

Where BitFlyerParentOrderRequest is:

```
{
  "order_method": "IFDOCO",
  "minute_to_expire": 10000,
  "time_in_force": "GTC",
  "parameters": [{
    "product_code": "BTC_JPY",
    "condition_type": "LIMIT",
    "side": "BUY",
    "price": 30000,
    "size": 0.1
  },
  {
    "product_code": "BTC_JPY",
    "condition_type": "LIMIT",
    "side": "SELL",
    "price": 32000,
    "size": 0.1
  },
  {
    "product_code": "BTC_JPY",
    "condition_type": "STOP_LIMIT",
    "side": "SELL",
    "price": 28800,
    "trigger_price": 29000,
    "size": 0.1
  }]
}
```

**Comment by dovelive** [comment]
Thank you @theo1985 
To tell you the truth, I tried that way too.
But it also returned the same error message as before.

Please refer the code below.

BitflyerParentOrderRequest.java
```
...
public class BitflyerParentOrderRequest {

    @JsonProperty("order_method")
    private final String orderMethod;

    @JsonProperty("time_in_force")
    private final String timeInForce;

    @JsonProperty("minute_to_expire")
    private final Integer minuteToExpire;

    @JsonProperty("parameters")
    private final List<BitflyerParentOrderParameter> parameters;

    public BitflyerParentOrderRequest(String orderMethod, Integer minuteToExpire, String timeInForce, List<BitflyerParentOrderSubParameter> parameters) {
        this.orderMethod = orderMethod;
        this.minuteToExpire = minuteToExpire;
        this.timeInForce = timeInForce;
        this.parameters = parameters;
    }

    public List<BitflyerParentOrderSubParameter> getParameters() {
        return parameters;
    }

    /**
     * @return the timeInForce
     */
    public String getTimeInForce() {
        return timeInForce;
    }

    /**
     * @return the minuteToExpire
     */
    public Integer getMinuteToExpire() {
        return minuteToExpire;
    }

    /**
     * @return the ordeMethod
     */
    public String getOrderMethod() {
        return orderMethod;
    }
}
```

```
  @POST
  @Path("me/sendparentorder")
  BitflyerParentOrderResponse placeParentOrder(@HeaderParam(ACCESS_KEY) String apiKey,
      @HeaderParam(ACCESS_TIMESTAMP) SynchronizedValueFactory<Long> nonce,
      @HeaderParam(ACCESS_SIGN) ParamsDigest paramsDigest,
      BitflyerParentOrderRequest request
      ) throws IOException, BitflyerException;
 ```

**Comment by theo1985** [comment]
OK, I recreated your issue and resolved:

```
  @POST
  @Path("me/sendparentorder")
  @Produces(MediaType.APPLICATION_JSON)
  @Consumes(MediaType.APPLICATION_JSON)
  BitflyerParentOrderResponse placeParentOrder(@HeaderParam(ACCESS_KEY) String apiKey,
                                               @HeaderParam(ACCESS_TIMESTAMP) SynchronizedValueFactory<Long> nonce,
                                               @HeaderParam(ACCESS_SIGN) ParamsDigest paramsDigest,
                                               BitflyerParentOrderRequest request
  ) throws IOException, BitflyerException;
```
and
```
public BitflyerParentOrderResponse placeParentOrder(String orderMethod, Integer minuteToExpire, String timeInForce, List<BitflyerParentOrderParameter> paramRequest) throws IOException {
        try {
            return bitflyer.placeParentOrder(apiKey, exchange.getNonceFactory(), signatureCreator, new BitflyerParentOrderRequest(orderMethod, minuteToExpire, timeInForce, paramRequest));
        } catch (BitflyerException e) {
            throw handleError(e);
        }
    }
```
gives: Exception in thread "main" org.knowm.xchange.exceptions.ExchangeException: org.knowm.xchange.bitflyer.dto.BitflyerException: Invalid product

**Comment by theo1985** [comment]
@dovelive has this resolved your issue?

**Comment by dovelive** [comment]
Yes.
It has solved.
Thank you.
