### ISSUE TITLE
Bitstamp Invalid nonce (HTTP status code: 403)

### ISSUE THREAD

**Issue by GeekQing** [timmolter/XChange#2220]
**When I invoke Bitstamp Exchange‘s API，occasionally I can encounter a "Invalid nonce (HTTP status code: 403)" error;**

`[2018-01-24 13:22:20] [ERROR] com.alphatouzi.ems.trading.gateway.BitStampTradingGateway - 获取持仓信息失败
com.alphatouzi.xchange.bitstamp.dto.BitstampException: Invalid nonce (HTTP status code: 403)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:125)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:240)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:158)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:401)
	at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:70)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2048)
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53)
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58)
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120)
	at com.sun.proxy.$Proxy85.getBalance(Unknown Source)
	at com.alphatouzi.xchange.bitstamp.service.BitstampAccountServiceRaw.getBitstampBalance(BitstampAccountServiceRaw.java:59)
	at com.alphatouzi.xchange.bitstamp.service.BitstampAccountService.getAccountInfo(BitstampAccountService.java:47)
	at com.alphatouzi.ems.trading.gateway.BitStampTradingGateway.crawPosition(BitStampTradingGateway.java:232)
	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)`

**I debug and print the nonce, found that the nonce is not duplicate.**

`[2018-01-24 13:22:11] [INFO ] com.alphatouzi.xchange.utils.nonce.CurrentTimeNonceFactory - Nonce: 1516771331069
[2018-01-24 13:22:19] [INFO ] com.alphatouzi.xchange.utils.nonce.CurrentTimeNonceFactory - Nonce: 1516771339777
[2018-01-24 13:22:20] [INFO ] com.alphatouzi.xchange.utils.nonce.CurrentTimeNonceFactory - Nonce: 1516771340002
[2018-01-24 13:22:20] [INFO ] com.alphatouzi.xchange.utils.nonce.CurrentTimeNonceFactory - Nonce: 1516771340273
[2018-01-24 13:22:20] [INFO ] com.alphatouzi.xchange.utils.nonce.CurrentTimeNonceFactory - Nonce: 1516771340968
[2018-01-24 13:22:30] [INFO ] com.alphatouzi.xchange.utils.nonce.CurrentTimeNonceFactory - Nonce: 1516771350002
`

And Then I watched the rescu source code，The function createValue() of NonceFactory and function invokeHttp() have surrounded by lock. 

`synchronized (lock) {
    invocation = RestInvocation.create(
            requestWriterResolver, methodMetadata, args, config.getDefaultParamsMap());
    connection = invokeHttp(invocation);
}`

Is there any solutions of this ? @mmazi @timmolter  Can you help me?

**Comment by mmazi** [comment]
I think this kind of errors are impossible to 100% avoid if you make concurrent requests to the API. 

There can be no guarantee that the Bitstamp API server will process almost-simultaneous requests in the same order as you've sent them from your side. This is due to both the nature of internet and Bitstamp's internal request processing mechanism (load balancing etc.)
