### ISSUE TITLE
CexIO: Nonce must be incremented

### ISSUE THREAD

**Issue by solovieff** [timmolter/XChange#2318]
```
Error performing exchange request to CexioExchange
org.knowm.xchange.exceptions.ExchangeException: Error getting balance. Nonce must be incremented
	at org.knowm.xchange.cexio.service.CexIOAccountServiceRaw.getCexIOAccountInfo(CexIOAccountServiceRaw.java:23)
	at org.knowm.xchange.cexio.service.CexIOAccountService.getAccountInfo(CexIOAccountService.java:37)
	at com.vember.crypto.CryptoAPIImporter.createAccountPortfolio(CryptoAPIImporter.java:203)
```

Suppose this is connected to timezones, tried two different ones, did not help.

**Comment by solovieff** [comment]
CurrentNanosecondTimeIncrementalNonceFactory works fine.

**Comment by makarid** [comment]
Did you solve your issue?If yes please close the issue.One question about CEX.io.Why you are using this exchange,they don't pay the withdraws?The internet is all over complains about them.I had also one bad experience with them.Be carefull!

**Comment by solovieff** [comment]
I just have it in my exchange list, so have to use. The issue is not fixed, using subclass with CurrentNanosecondTimeIncrementalNonceFactory is just a workaround.

**Comment by gewure** [comment]
Just reactivating on this because we got a similiar issue with cex.io
