### ISSUE TITLE
I just started getting a weird error

### ISSUE THREAD

**Issue by ThatPersonInTheMirror** [timmolter/XChange#2319]
It was just working then I did a maven project update because it said I had an error now i get this

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoClassDefFoundError: javax/ws/rs/PATCH
	at si.mazi.rescu.RestMethodMetadata.<clinit>(RestMethodMetadata.java:47)
	at si.mazi.rescu.RestInvocationHandler.getMetadata(RestInvocationHandler.java:175)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:106)
	at com.sun.proxy.$Proxy10.tick(Unknown Source)
	at org.knowm.xchange.kucoin.service.KucoinMarketDataServiceRaw.getKucoinTickers(KucoinMarketDataServiceRaw.java:35)
	at org.knowm.xchange.kucoin.service.KucoinMarketDataService.getMetadata(KucoinMarketDataService.java:89)
	at org.knowm.xchange.kucoin.KucoinExchange.remoteInit(KucoinExchange.java:50)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:111)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:134)
	at com.bishop.KucoinBotMaven.KucoinUtils.getExchange(KucoinUtils.java:16)
	at com.bishop.KucoinBotMaven.Calculate.<init>(Calculate.java:56)
	at com.bishop.KucoinBotMaven.kuBotMain.main(kuBotMain.java:9)
Caused by: java.lang.ClassNotFoundException: javax.ws.rs.PATCH
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 12 more

can anyone help me out with this?

**Comment by ThatPersonInTheMirror** [comment]
you need to add this dependence to fix it
<dependency>
    <groupId>javax.ws.rs</groupId>
    <artifactId>javax.ws.rs-api</artifactId>
    <version>2.1-m07</version>
</dependency>
