### ISSUE TITLE
BIBOX-4.3.4-SNAPSHOT-develop-placeLimitOrder-GET-NPE

### ISSUE THREAD

**Issue by lrqstudy** [timmolter/XChange#2357]
CODE

        Exchange exchange = ExchangeFactory.INSTANCE.createExchange(exSpec);
        BiboxTradeServiceRaw tradeService =(BiboxTradeServiceRaw) exchange.getTradeService();
        LimitOrder limitOrder=new LimitOrder.Builder(Order.OrderType.ASK,new CurrencyPair("EOS","BTC"))
                .limitPrice(new BigDecimal("0.00082"))
                .originalAmount(new BigDecimal("1"))
                .build();//EOS_BTC 

        Object result = tradeService.placeBiboxLimitOrder(limitOrder);
        System.out.println(result);

RESULT:

Exception in thread "main" java.lang.NullPointerException
	at org.knowm.xchange.bibox.dto.BiboxSingleResponse.get(BiboxSingleResponse.java:15)
	at org.knowm.xchange.bibox.service.BiboxTradeServiceRaw.placeBiboxLimitOrder(BiboxTradeServiceRaw.java:39)
	at com.libra.exchange.exchanges.bibox.BiboxExchangeUtils.test(BiboxExchangeUtils.java:79)
	at com.libra.exchange.exchanges.bibox.BiboxExchangeUtils.main(BiboxExchangeUtils.java:60)
Disconnected from the target VM, address: '127.0.0.1:57166', transport: 'socket'

**Comment by odrotleff** [comment]
can you try again with the latest version of the develop branch. I think PR #2350 should solve the issue.

**Comment by lrqstudy** [comment]
thx, the code is ok after PR#2350,
