### ISSUE TITLE
Updating commons-codec1.3 to commons-codec 1.4 and above

### ISSUE THREAD

**Issue by makarid** [timmolter/XChange#2402]
Hello, i just came across and error : 
java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.encodeBase64URLSafeString([B)Ljava/lang/String;

It seems that in the xchange-core package the version of commons-codec library is 1.3.I search the Internet and found that this error message pops up when the version is below 1.4. Can we update the commons-codec library of code package to 1.4 or greater. Thanks

**Comment by timmolter** [comment]
Can you post the entire stack trace?

**Comment by makarid** [comment]
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.encodeBase64URLSafeString([B)Ljava/lang/String;
	at com.auth0.jwt.JWTCreator.sign(JWTCreator.java:283)
	at com.auth0.jwt.JWTCreator.access$100(JWTCreator.java:23)
	at com.auth0.jwt.JWTCreator$Builder.sign(JWTCreator.java:264)
	at org.knowm.xchange.quoine.service.QuoineSignatureDigest.digestParams(QuoineSignatureDigest.java:36)
	at si.mazi.rescu.Params.digestAll(Params.java:199)
	at si.mazi.rescu.RestInvocation.create(RestInvocation.java:147)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:116)
	at com.sun.proxy.$Proxy17.executions(Unknown Source)
	at org.knowm.xchange.quoine.service.QuoineTradeServiceRaw.executions(QuoineTradeServiceRaw.java:105)
	at org.knowm.xchange.quoine.service.QuoineTradeService.getTradeHistory(QuoineTradeService.java:110)
	at com.Test.ExchangeInit.downloadTradeHistory(ExchangeInit.java:163)
	at com.Test.QryptosMain.main(QryptosMain.java:30)

**Comment by mmazi** [comment]
You can probably fix this in XChange by either <exclude>ing the commons-codec dependency from the rescu dependency, or by stating an explicit dependency on the version of commons-codec that you want to use in XChange.

**Comment by mmazi** [comment]
I think XChange doesn't use rescu's oauth feature (that in turn requires commons-codec), so I think the simplest and at the same time the most correct thing to do is to simply `<exclude>` commons-codec from the rescu dependency in XChange.

**Comment by makarid** [comment]
Thanks for your response! I will do that.

**Comment by timmolter** [comment]
@makarid I already did it. Please let me know if it solved your issue.

**Comment by makarid** [comment]
At last i found the problem! The problem wasn't on the Xchange library but on the streaming-Xchange library. In my project i have add both libraries, info.bitrich and org.knowm. For some reason when i was trying to execute a line from Quoinex Xchange library which needed Base64, instead to run the codec from Xchange library it was running the codec from streaming-Xchange library which was 1.3 version. Now i remove the info.bitrich library and my program worked. So maybe the streaming-Xchange library should update the codec library they use.Thank you so much for your help,both of you!
