### ISSUE TITLE
Bibox apikey signature fail

### ISSUE THREAD

**Issue by kernelogic** [timmolter/XChange#2405]
Hello, I am trying to use bibox with API but unsuccessful. My code is nothing but to get balance. I don't think I copy/pasted api key/secret wrong.

{"error":{"code":"3025","msg":"apikey签名验证失败"}} 
org.knowm.xchange.exceptions.ExchangeException: 3025: apikey签名验证失败
	at org.knowm.xchange.bibox.service.BiboxBaseService.throwErrors(BiboxBaseService.java:33)
	at org.knowm.xchange.bibox.service.BiboxAccountServiceRaw.getBiboxAccountInfo(BiboxAccountServiceRaw.java:27)
	at org.knowm.xchange.bibox.service.BiboxAccountService.getAccountInfo(BiboxAccountService.java:29)
	at aaaaaaa.AbstractHelper.buy(AbstractHelper.java:73)
	at aaaaaaa.BiboxHelper.main(BiboxHelper.java:17)

**Comment by makarid** [comment]
Maybe it is the same issue as mine. @timmolter is it possible that this error is because the codec 1.3 deletion?

**Comment by makarid** [comment]
@kernelogic can you please tell me the version you use on core package?

**Comment by cymp** [comment]
Same problem here, haven't investigated yet.

**Comment by kernelogic** [comment]
I tried both latest release and snapshot even directly cloned from develop branch. All the same.

**Comment by makarid** [comment]
@kernelogic i believe that the new fix of @timmolter has fix your problem also.Please check it

**Comment by cymp** [comment]
I just tested, it now works, you can close I guess.
