### ISSUE TITLE
Kucoin UNAUTH - Signature verification failed (HTTP status code: 401)

### ISSUE THREAD

**Issue by makarid** [timmolter/XChange#2406]
Hello,is there anyone that get the same error? I am trying to get my balance on of a Currency on Kucoin.I have created a new API key in order to test it,but the same issue exists.

Exception in thread "main" org.knowm.xchange.exceptions.ExchangeException: UNAUTH - Signature verification failed (HTTP status code: 401)
	at org.knowm.xchange.kucoin.service.KucoinAccountServiceRaw.getKucoinBalances(KucoinAccountServiceRaw.java:31)
	at org.knowm.xchange.kucoin.service.KucoinAccountService.getAccountInfo(KucoinAccountService.java:40)
	at com.Test.ExchangeInit.getBaseCurrencyBalanceTotal(ExchangeInit.java:133)
	at com.Test.QryptosMain.main(QryptosMain.java:30)

**Comment by makarid** [comment]
This is issue exist only on 4.3.5 version.

**Comment by timmolter** [comment]
It's probably related to my commit #2b246fcd8a49e8d542e4ef30626d14b31f453879. Sorry. I'll try to make it better tomorrow morning.

**Comment by makarid** [comment]
Thanks!

**Comment by timmolter** [comment]
OK, could you test it now?

**Comment by cymp** [comment]
@timmolter I will test https://github.com/timmolter/XChange/issues/2405 and will tell you if you can close the issue

**Comment by makarid** [comment]
@timmolter i am testing also

**Comment by makarid** [comment]
@timmolter it works! It has fix also the Kucoin 0 LTC balance issue that i have post.Thanks!

**Comment by timmolter** [comment]
Great! Glad to hear it works now.
