### ISSUE TITLE
BitbayMarketDataService.getOrderBook returns 509

### ISSUE THREAD

**Issue by walec51** [timmolter/XChange#2449]
The given currency codes are correct. I have no idea why this is not working...

si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 509
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120)
	at com.sun.proxy.$Proxy117.getBitbayOrderBook(Unknown Source)
	at org.knowm.xchange.bitbay.service.BitbayMarketDataServiceRaw.getBitbayOrderBook(BitbayMarketDataServiceRaw.java:33)
	at org.knowm.xchange.bitbay.service.BitbayMarketDataService.getOrderBook(BitbayMarketDataService.java:37)

**Comment by walec51** [comment]
This is strange - it seams to have something to do with reusing the same thread for another request:

2018-03-29 04:02:40.796 DEBUG 17394 --- [askScheduler-10] si.mazi.rescu.HttpTemplate               : Executing GET request at https://bitbay.net/API/Public/XRPPLN/orderbook.json
2018-03-29 04:02:40.797 TRACE 17394 --- [askScheduler-10] si.mazi.rescu.HttpTemplate               : Request body = 
2018-03-29 04:02:40.797 TRACE 17394 --- [askScheduler-10] si.mazi.rescu.HttpTemplate               : Request headers = {Accept=application/json}
2018-03-29 04:02:40.797 TRACE 17394 --- [askScheduler-10] si.mazi.rescu.HttpTemplate               : Header request property: key='Accept-Charset', value='UTF-8'
2018-03-29 04:02:40.797 TRACE 17394 --- [askScheduler-10] si.mazi.rescu.HttpTemplate               : Header request property: key='User-Agent', value='ResCU JDK/6 AppleWebKit/535.7 Chrome/16.0.912.36 Safari/535.7'
2018-03-29 04:02:40.797 TRACE 17394 --- [askScheduler-10] si.mazi.rescu.HttpTemplate               : Header request property: key='Accept', value='application/json'

2018-03-29 04:02:40.882 DEBUG 17394 --- [askScheduler-10] si.mazi.rescu.HttpTemplate               : Request http status = 200
2018-03-29 04:02:40.882 TRACE 17394 --- [askScheduler-10] si.mazi.rescu.HttpTemplate               : Http call returned 200; response body:
{"bids":[[1.95,14],[1.94,200],[1.93,25621.839377],[1.92,3806.412665],[1.91,2328.22085465],[1.90,49016.190087],[1.89,334.060106],[1.88,1142.077872],[1.87,670.903048],[1.86,1186.771441],[1.85,11335.463323],[1.84,436.963478],[1.83,512.655519],[1.82,2750.901099],[1.81,5292.558011],[1.8,5736.574999],[1.79,10101],[1.78,300],[1.77,56.508475],[1.76,1236.813636],[1.75,2230.588571],[1.74,1],[1.73,30],[1.72,21.744186],[1.71,10000],[1.7,5413.495942],[1.69,2],[1.68,44.642857],[1.67,10078.491018],[1.66,602.409639],[1.65,181.818182],[1.64,100],[1.62,64.586420],[1.61,349.093168],[1.6,489.125],[1.58,620.449367],[1.56,689.517269],[1.55,30.15],[1.53,1.960784],[1.52,328.947368],[1.51,1145],[1.5,24521.839667],[1.45,180.310345],[1.44,200],[1.42,2.112676],[1.41,709.219858],[1.4,1783.842856],[1.37,208.605839],[1.35,74.074074],[1.32,480.386364],[1.3,578.946154],[1.28,316.40625],[1.26,317.460317],[1.25,300],[1.24,818.540323],[1.2,45.833333],[1.19,100.5],[1.11,500],[1.1,160.043],[1.08,92.592593],[1.07,23364.485981],[1.02,100],[1.01,1103.1],[1,310.65],[0.99,50.505051],[0.97,103.092784],[0.92,108.695652],[0.89,0.202247],[0.88,568.181818],[0.87,114.942529],[0.82,121.95122],[0.7,14285.714286],[0.67,373.134328],[0.24,45],[0.23,1],[0.14,628.571429],[0.03,1666.666667],[0.01,130]],"asks":[[1.97,1000],[1.98,25567.826709],[2,9501.650117],[2.01,305.76728],[2.02,1681.68],[2.03,2829.013339],[2.04,883.935708],[2.05,4933.30392968],[2.06,675.728760],[2.07,6206.55092307],[2.08,3635.002422],[2.09,124.73688058],[2.1,354.87370968],[2.11,303.57363188],[2.12,106.57981660],[2.13,794.09007692],[2.14,1627.964],[2.15,2432.84576028],[2.16,101.89680645],[2.17,74.775],[2.18,371.796744],[2.19,4621.144485],[2.2,8395.126559],[2.21,1150.074635],[2.22,218.536352],[2.23,1012.03],[2.24,72.313122],[2.25,2887.43507736],[2.26,149.72731],[2.27,1764.267147],[2.28,300],[2.29,3181.466078],[2.3,5570.53765364],[2.31,6705.457898],[2.32,2157.78623721],[2.33,164.15984996],[2.34,668.86828656],[2.35,1283.113852],[2.36,2157.693337],[2.37,924.601226],[2.38,1278.253542],[2.39,4919.433020],[2.4,3413.304054],[2.41,4595.48469886],[2.42,1703.915075],[2.43,540.421831],[2.44,9909.83453009],[2.45,5202.277843],[2.46,553.178917],[2.47,3347.334695],[2.48,1003.18155303],[2.49,4118.13237368],[2.5,199159.01863184],[2.51,794.05083695],[2.52,275.91259029],[2.53,127.11536816],[2.54,2215.52996023],[2.55,348.247013],[2.56,228],[2.57,1022],[2.59,217.841671],[2.6,102377.737426],[2.61,362.264042],[2.62,498.75],[2.63,431.050201],[2.64,132.676495],[2.65,1018.990907],[2.66,124.633345],[2.67,353.200732],[2.68,3.009094],[2.7,100.855],[2.71,53.94205],[2.75,894.49939],[2.76,15],[2.77,10],[2.78,1219.346258],[2.79,40],[2.8,75065.666715],[2.81,483.17511],[2.82,1168.565310],[2.85,9.96],[2.87,20],[2.88,230.149],[2.9,1238.259259],[2.92,11186.311956],[2.97,81.950617],[2.98,13],[2.99,1031.3125],[3,8481.165626],[3.01,41],[3.02,5],[3.05,100.779352],[3.06,177.8725],[3.1,798.640786],[3.15,65],[3.19,65],[3.2,936.928022],[3.21,307],[3.22,70],[3.23,175.909543],[3.24,10],[3.25,4950.863064],[3.27,1571.210632],[3.28,219],[3.29,81],[3.3,489.275174],[3.34,9.958],[3.35,744],[3.39,177],[3.4,135.518908],[3.42,16.791122],[3.45,508.33781],[3.47,30.111686],[3.48,500],[3.49,757.534907],[3.5,399.596847],[3.54,1200],[3.6,26.99275],[3.64,83],[3.7,300],[3.74,74.044525],[3.8,200],[3.9,100],[3.92,20.5144],[3.95,5101],[4,949.122254],[4.1,100],[4.2,2.685769],[4.5,450],[4.55,304.322307],[4.6,894.77683],[4.92,41.367261],[4.99,6939.889725],[5,934.427585],[5.2,0.21459],[5.28,40.47561],[5.4,65.98],[5.68,501.456797],[6,3699.610709],[6.59,772.116206],[6.8,8],[7.3,137.7829],[7.5,42.910349],[7.54,25.111719],[7.87,1.104753],[8,2348.969857],[8.8,115],[8.88,3041.590091],[9,50],[9.1,140],[9.2,10],[9.3,209],[9.5,2000],[9.59,1469.501136],[9.98,17.767806],[9.99,11],[10,1787.556063],[10.05,2],[10.3,69.68],[10.75,9.907421],[10.8,105.168776],[11.84,49.985865],[12,1274.3401],[13.45,1073.753206],[13.55,5],[15,2005.772152],[16,1.347],[16.57,76.47238],[20,440.888322],[20.2,10],[22,4],[22.32,4.5],[23,216.866116],[25,14],[30,50],[31.49,671.113492],[33,4120],[50,483.077321],[55,3],[75,100],[79,5],[80,1270.918368],[82.35,124.96205],[90,1],[99,38.304103],[99.38,1972.538688],[100,650.868684],[161,2.4],[194,62.825351],[195.26,301.86445],[199,25],[200,1266.454954],[999,370.77],[1000,471.416748],[1002,10],[1002.01,2],[1002.15,10],[1002.35,10],[1002.38,21],[1002.44,12],[1002.48,8],[1200,0.997],[1500,35],[2851.13,20.15563],[5000,17.549761],[6000,0.20446],[8000,1],[10000,466.590427],[14500,3],[22000,2],[29400,1000],[100000,1.215836]]}
2018-03-29 04:02:40.883 DEBUG 17394 --- [askScheduler-10] si.mazi.rescu.HttpTemplate               : Executing GET request at https://bitbay.net/API/Public/XRPUSD/orderbook.json
2018-03-29 04:02:40.883 TRACE 17394 --- [askScheduler-10] si.mazi.rescu.HttpTemplate               : Request body = 
2018-03-29 04:02:40.883 TRACE 17394 --- [askScheduler-10] si.mazi.rescu.HttpTemplate               : Request headers = {Accept=application/json}
2018-03-29 04:02:40.883 TRACE 17394 --- [askScheduler-10] si.mazi.rescu.HttpTemplate               : Header request property: key='Accept-Charset', value='UTF-8'
2018-03-29 04:02:40.883 TRACE 17394 --- [askScheduler-10] si.mazi.rescu.HttpTemplate               : Header request property: key='User-Agent', value='ResCU JDK/6 AppleWebKit/535.7 Chrome/16.0.912.36 Safari/535.7'
2018-03-29 04:02:40.883 TRACE 17394 --- [askScheduler-10] si.mazi.rescu.HttpTemplate               : Header request property: key='Accept', value='application/json'

2018-03-29 04:02:41.265 DEBUG 17394 --- [askScheduler-10] si.mazi.rescu.HttpTemplate               : Request http status = 509
2018-03-29 04:02:41.266 TRACE 17394 --- [askScheduler-10] si.mazi.rescu.HttpTemplate               : Http call returned 509; response body:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>509 unused</title></head><body><h1>unused</h1><p>The server encountered an internal error ormisconfiguration and was unable to completeyour request.</p><p>Please contact the server administrator, <a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="b0d1d4ddd9def0d2d9c4d2d1c99ec0dc">[email&#160;protected]</a> and inform them of the time the error occurred,and anything you might have done that may havecaused the error.</p><p>More information about this error may be availablein the server error log.</p><script data-cfasync="false" src="/cdn-cgi/scripts/d07b1474/cloudflare-static/email-decode.min.js"></script></body></html>

**Comment by walec51** [comment]
turns out this was due to me exceeding the APIs request limit
https://github.com/timmolter/XChange/issues/1632
