### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: 

### ISSUE THREAD

**Issue by timmolter** [timmolter/XChange#52]
I received the following Email:

I thought I would try out the Canadian VirtEx exchange ticker so I could setup some auto arbitrage alerts as well, however I'm getting the following exceptions (xchange-cavirtex-1.4.1-20130201.151127-4.jar):

Exchange virtEx = ExchangeFactory.INSTANCE.createExchange(VirtExExchange.class.getName());
mMarketDataVirtEx = virtEx.getPollingMarketDataService();
Ticker ticker = mMarketDataVirtEx.getTicker(Currencies.BTC, Currencies.CAD);

com.xeiam.xchange.rest.HttpException: Problem GETing (IO)
	at com.xeiam.xchange.rest.HttpTemplate.executeRequest(HttpTemplate.java:197)
	at com.xeiam.xchange.rest.HttpTemplate.executeRequest(HttpTemplate.java:97)
	at com.xeiam.xchange.rest.RestInvocationHandler.invokeHttp(RestInvocationHandler.java:61)
	at com.xeiam.xchange.rest.RestInvocationHandler.invoke(RestInvocationHandler.java:56)
	at sun.proxy.$Proxy13.getTicker(Unknown Source)
	at com.xeiam.xchange.virtex.service.marketdata.polling.VirtExPollingMarketDataService.getTicker(VirtExPollingMarketDataService.java:73)
	at main.Main.main(Main.java:147)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at com.xeiam.xchange.rest.HttpTemplate.executeRequest(HttpTemplate.java:186)
	... 6 more
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getHeaderField(Unknown Source)
	at com.xeiam.xchange.rest.HttpTemplate.getResponseEncoding(HttpTemplate.java:264)
	at com.xeiam.xchange.rest.HttpTemplate.executeRequest(HttpTemplate.java:185)
	... 6 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at sun.security.validator.Validator.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 21 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.security.cert.CertPathBuilder.build(Unknown Source)
	... 27 more

**Comment by PeterNSteinmetz** [comment]
Perhaps also catching the exception and clarifying the nature of the problem could be helpful. The exception stack trace can be a bit hard to understand.

**Comment by timmolter** [comment]
@mmazi Do you think rescu would be a good place to catch this specific exception and enhance the error message with a brief hint towards the fix?

**Comment by mmazi** [comment]
@timmolter yes, rescu would probably be the place to do it. Can you please open an issue there?

**Comment by ducmanhtkhd** [comment]
How can this link only appears when running programs
 [URIName: http://EVIntl-crl.verisign.com/EVIntl2006.crl]     ?

**Comment by ducmanhtkhd** [comment]
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.security.KeyStore;
import java.security.PublicKey;
import java.security.cert.Certificate;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.util.Enumeration;

public class Main {
	public static void main(String[] args) throws Exception {
		Main readCertificateFile = new Main();
		// Path of the certificate file
		FileInputStream fis = new FileInputStream("BCSE_Test_Client_BkavCA_.cer");
		CertificateFactory cf = CertificateFactory.getInstance("X.509");
		 java.security.cert.Certificate cert = cf.generateCertificate(fis);
	        System.out.println();
	        System.out.println("Certificate Details: ");
	        /*Returns the type of this certificate factory*/
	        System.out.println("Type = " + cert.getType());        
	        System.out.println("toString = " + cert.toString());
	        PublicKey key = cert.getPublicKey();
	        System.out.println();
	        System.out.println("PublicKey Object Info: ");
	        System.out.println("Algorithm = " + key.getAlgorithm());
	        System.out.println("Format = " + key.getFormat());
	        System.out.println("toString = " + key.toString());
	        // save/import certificate into keystore
	        readCertificateFile.saveCert(cert);
	    }

	private void saveCert(Certificate cert) throws Exception {
		KeyStore keyStore = KeyStore.getInstance("JKS");
		keyStore.load(null, null);
		// import your certificate into keystore
		keyStore.setCertificateEntry("BCSE_Test_Client_BkavCA_", cert);
		// name of keystore "
		File file = new File(".", "BCSE_Test_Client_BkavCA_");
		keyStore.store(new FileOutputStream(file), "1".toCharArray());
	}

}

**Comment by JanisSharma** [comment]
You need to add the certificate for App2 to the truststore file of the used JVM located at %JAVA_HOME%libsecuritycacerts.

First you can check if your certificate is already in the truststore by running the following command: keytool -list -keystore "%JAVA_HOME%/jre/lib/security/cacerts" (you don’t need to provide a password)

If your certificate is missing, you can get it by downloading it with your browser and add it to the truststore with the following command:

keytool -import -noprompt -trustcacerts -alias <AliasName> -file <certificate> -keystore <KeystoreFile> -storepass <Password>

After import you can run the first command again to check if your certificate was added.

Full Source Code [Here](https://icetutor.com/question/resolving-javax-net-ssl-sslhandshakeexception-sun-security-validator-validatorexception-pkix-path-building-failed-error)
