### ISSUE TITLE
Version 3.0.0 comments thread

### ISSUE THREAD

**Issue by timmolter** [timmolter/XChange#841]
Hi Everyone. I just pushed a wide-sweeping refactor. The main motivation behind it was to provide a way to "inject" metadata into each Exchange. This metadata is data associated with exchanges that is somewhat static, but does tend to change over time. Examples include, currency pairs, max polling rates, scaling factors, etc. 

This new feature works by having each exchange module provide a json file in `resources` that matches the exchange name in the ExchangeConfiguration. During creation of the exchange, the file is loaded into an object called `MetaData`. I will be expanding this object over the next days to include more parameters. I plan to add a way to specify an override file from any local path.

The metadata is available at the top of the class hierarchy: `BaseExchange`. This makes the metadata available to all services, including streaming now.

I was also motivated to do this because of the upcoming release I want to do. I always try to "clean things up" before each release. While going through the code, I noticed that many of the implementations have gone a bit of track. That's OK, but it's my job to try to keep everything consistent, and I changed a few things for the sake of consistency. For example, where Collections, List and Sets were, I picked List. Sometimes `synchronized` was used, and I removed it. Gasp! The point is, if it's important, let's decide to add something or not and then add it throughout and not just "here and there".

Please voice your opinions and report anything that I broke. Also, if you have anything general to say about any part of XChange, now would be a good time. I'll be working through stuff over the next week, trying to get 3.0.0 released.

**Comment by zylum-studios** [comment]
Had to revert to 2.1.0 as polling account info seemed to be locking. Didn't really dig into it - sorry.

**Comment by timmolter** [comment]
@hbar-digital what exchange has the problem? What method call? Thanks.

**Comment by DISSIDIA-986** [comment]
16:59:08.476 [default] [main] DEBUG com.xeiam.xchange.ExchangeFactory - Creating exchange from specification 
16:59:08.718 [default] [main] WARN  com.xeiam.xchange.BaseExchange - An exception occured while loading the metadata file from the classpath. This may lead to unexpected results. com.fasterxml.jackson.core.JsonParseException: Unexpected character (']' (code 93)): expected a value
 at [Source: sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream@4ee91125; line: 7, column: 5]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419) ~[jackson-core-2.4.0.jar:2.4.0]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508) ~[jackson-core-2.4.0.jar:2.4.0]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:437) ~[jackson-core-2.4.0.jar:2.4.0]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2329) ~[jackson-core-2.4.0.jar:2.4.0]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:794) ~[jackson-core-2.4.0.jar:2.4.0]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:690) ~[jackson-core-2.4.0.jar:2.4.0]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:226) ~[jackson-databind-2.4.0.jar:2.4.0]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:206) ~[jackson-databind-2.4.0.jar:2.4.0]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25) ~[jackson-databind-2.4.0.jar:2.4.0]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538) ~[jackson-databind-2.4.0.jar:2.4.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:348) ~[jackson-databind-2.4.0.jar:2.4.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1058) ~[jackson-databind-2.4.0.jar:2.4.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:268) ~[jackson-databind-2.4.0.jar:2.4.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:124) ~[jackson-databind-2.4.0.jar:2.4.0]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051) ~[jackson-databind-2.4.0.jar:2.4.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2192) ~[jackson-databind-2.4.0.jar:2.4.0]
	at com.xeiam.xchange.BaseExchange.applySpecification(BaseExchange.java:89) ~[xchange-core-3.0.0-SNAPSHOT.jar:na]
	at com.xeiam.xchange.okcoin.OkCoinExchange.applySpecification(OkCoinExchange.java:30) [xchange-okcoin-3.0.0-SNAPSHOT.jar:na]
	at com.xeiam.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:91) [xchange-core-3.0.0-SNAPSHOT.jar:na]
	at com.cnbit.common.main.BalanceTask.main(BalanceTask.java:27) [classes/:na]

Exception in thread "main" java.lang.ClassCastException: java.util.Arrays$ArrayList cannot be cast to java.util.ArrayList
	at com.xeiam.xchange.okcoin.service.polling.OkCoinBasePollingService.<init>(OkCoinBasePollingService.java:34)
	at com.xeiam.xchange.okcoin.service.polling.OkCoinMarketDataServiceRaw.<init>(OkCoinMarketDataServiceRaw.java:28)
	at com.xeiam.xchange.okcoin.service.polling.OkCoinMarketDataService.<init>(OkCoinMarketDataService.java:23)
	at com.xeiam.xchange.okcoin.OkCoinExchange.applySpecification(OkCoinExchange.java:43)
	at com.xeiam.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:91)
	at com.cnbit.common.main.BalanceTask.main(BalanceTask.java:27)

**Comment by DISSIDIA-986** [comment]
I just updated to 3.0,then PollingAccountService and PollingMarketDataService encountered error.I don't know why.thanks

**Comment by DISSIDIA-986** [comment]
I see,should add okcoin.json to the classpath,but I konw OKCoin's currency_pairs,but the site‘s poll rate limitions,I'm not quite sure.

**Comment by timmolter** [comment]
@DISSIDIA-986 I just pushed a fix. Please try it now.

**Comment by jheusser** [comment]
Maybe it would be better to release 2.2.0 first as the SNAPSHOT was around for quite some time? There are a lot of fixes/changes in there I depend on without wanting to refactor to include 3.0.0 changes (which are definitely good and I'll comment on it later on as well).

**Comment by DISSIDIA-986** [comment]
bitvc.json has an extra ","

**Comment by timmolter** [comment]
@DISSIDIA-986 Fixed. Thanks.

@jheusser I think if I had to do it over from the beginning I would do it that way, but right now I just want to move forward with 3.0.0, as I don't have the extra time to think about a 2.2.0 release. I foresee pushing a 3.0.0 release very soon actually. I hope everyone can upgrade, test, and give the thumbs up for a release. For your point of view, you'll need to change import namespaces, and besides testing functionality, there shouldn't be too much more to change. Functionally, it should all be the same.

**Comment by jheusser** [comment]
@timmolter ok thanks, makes sense

**Comment by Panchen** [comment]
I am struggling with BitStamp account fees in 3.0.0. I used to use:

    Exchange bitStamp = BitStampAccount.createExchange();
    PollingAccountService accountServiceBS = bitStamp.getPollingAccountService();
    // BitStamp fees are charged on a sliding scale based on trading over last 30 days. Get current fee.
    feesBS = accountServiceBS.getAccountInfo().getTradingFee().movePointLeft(2);

I can't find in the re-factored Exchange.getMetaData() or in examples. 
How should I access this dynamic info now?

NB I tried staying on snapshot 2.2.0 but it appears to be re-factored in there so I would rather upgrade to 3.0.0 rather than downgrade to the last release. Any assistance much appreciated.

**Comment by timmolter** [comment]
@Panchen This was removed as described in issue #838. I still need to add it back into the metadata, as proposed. I'll do that ASAP and report back here.

**Comment by rafalkrupinski** [comment]
> feesBS = accountServiceBS.getAccountInfo().getTradingFee().movePointLeft(2);

Would be nice if all the fees be normalized to fractions.

**Comment by timmolter** [comment]
@Panchen The latest snapshot should have the function back in place. I reverted my previous changes for AccountInfo.

**Comment by Panchen** [comment]
Perfect - works again. Thanks.

**Comment by timmolter** [comment]
@Panchen would you be willing to provide a sample Bitstamp AccountInfo raw JSON document for our unit tests? I think the one we have is now somewhat outdated. You can and should of course redact your personal info from it. You can get it by setting the log level to TRACE in logback.xml.

**Comment by rafalkrupinski** [comment]
@timmolter questions abound fields in MetaData class:

While I understand the need for maxPrivate/PublicPollPerTime, why are there four of each?

What *CurrencyMultiplier fields hold?

Could you please add some javadocs?

**Comment by Panchen** [comment]
@timmolter I checked the raw JSON returned from accountServiceBS.getAccountInfo() in my code above versus the XChange/xchange-bitstamp/src/test/resources/account/example-accountinfo-data.json file. The parameter+value pairs currently returned by BitStamp are identical to the existing canned data test file, even though it is 2 years old. Let me know the location / format of the existing unit test file if you need more test data.

**Comment by timmolter** [comment]
Thanks @Panchen !

**Comment by rafalkrupinski** [comment]
@timmolter since the list of currency pairs available at the exchange is accessible from the MetaData, are we removing BasePollingService.getExchangeSymbols() ?

**Comment by timmolter** [comment]
@rafalkrupinski Yes, I'll add JavaDocs. To answer your question, some exchanges (ANX) have [different rates for different time windows](http://docs.anxv2.apiary.io/):

>API Usage Control
We have implement control on API usage to provide a stable environment for everybody to use.
Currently all users and IP addresses are throttled to 30 request of any type per second. You will get an error result if you are throttled.
Additionally there is a max of 60 requests per ten seconds and 50,000 requests per hour.
Information queries - such a get depth/results/ticker are throttled to 5 per second.
Finally there is a maximum of 50 open orders at any one time, with a total of 50 adds per hour.

I put it in there for now, but it's a work in progress. Your thoughts are welcomed.

I think `BasePollingService.getExchangeSymbols()` must stay and should stay as it provides an important function even with `MetaData`. Say the exchange provides an API endpoint from which we can poll the CurrencyPairs. For that exchange implementation, we would implement that method to call the REST API. For others with no such endpoint, we pull in the `MetaData`. See what I mean?

I'd also like to do something similar in the TradeService for a method like `getTradeMetatData`. Maybe parts of that object would be populated from one or more REST API calls, and/or fully or partially from the MeatData. That's my idea for now anyway. I think it will work out well.

**Comment by rafalkrupinski** [comment]
> To answer your question, some exchanges (ANX) have different rates for different time windows

From what I see across xchange DTOs, xchange doesn't support an union of all possible return values from all the exchanges, but a reasonably common subset. There might be 5 or 15 seconds or minutes counters - you want add them all? I hope not.

> See what I mean?

I see what you mean, but I'm still not sure about keeping getExchangeSymbols. Maybe we could replace it with getMetaData method that would return current remote information supplemented with local data from $exchange.json.
