### ISSUE TITLE
NullPointerException because bitstamp diff_order_book channel does not provide timestamp

### ISSUE THREAD

**Issue by sebster** [timmolter/XChange#846]
In BitstampAdapters.java:

Date date = new Date(bitstampOrderBook.getTimestamp() * timeScale); // polled order books provide a timestamp in seconds, stream in ms

The bitstampOrderBook.getTimestamp() method returns null and causes a null pointer exception:

Exception in thread "pusher-java-client eventQueue" java.lang.NullPointerException
	at com.xeiam.xchange.bitstamp.BitstampAdapters.adaptOrderBook(BitstampAdapters.java:71)
	at com.xeiam.xchange.bitstamp.service.streaming.BitstampPusherService.parseOrderBook(BitstampPusherService.java:203)
	at com.xeiam.xchange.bitstamp.service.streaming.BitstampPusherService.access$1(BitstampPusherService.java:200)
	at com.xeiam.xchange.bitstamp.service.streaming.BitstampPusherService$2.onEvent(BitstampPusherService.java:187)
	at com.pusher.client.channel.impl.ChannelImpl$1.run(ChannelImpl.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by timmolter** [comment]
Fixed. See latest commit.

**Comment by sebster** [comment]
Thanks for the quick fix! It works now! :)
