### ISSUE TITLE
Unit test failure on campbx

### ISSUE THREAD

**Issue by br0x** [timmolter/XChange#853]
Running com.xeiam.xchange.campbx.service.marketdata.TickerFetchIntegration
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.733 sec <<< FAILURE! - in com.xeiam.xchange.campbx.service.marketdata.TickerFetchIntegration
tickerFetchTest(com.xeiam.xchange.campbx.service.marketdata.TickerFetchIntegration)  Time elapsed: 1.73 sec  <<< ERROR!
si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 403
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:106)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:137)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:125)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:104)
	at com.sun.proxy.$Proxy13.getTicker(Unknown Source)
	at com.xeiam.xchange.campbx.service.polling.CampBXMarketDataServiceRaw.getCampBXTicker(CampBXMarketDataServiceRaw.java:30)
	at com.xeiam.xchange.campbx.service.polling.CampBXMarketDataService.getTicker(CampBXMarketDataService.java:34)
	at com.xeiam.xchange.campbx.service.marketdata.TickerFetchIntegration.tickerFetchTest(TickerFetchIntegration.java:24)

Results :

Tests in error: 
  TickerFetchIntegration.tickerFetchTest:24 » HttpStatusIO HTTP status code was ...

**Comment by timmolter** [comment]
I recently added integration tests for all modules, which ping the exchanges for a Ticker as a sanity check. When there is a failure there are three options:

1. run mvn with the no tests flag
1. run `mvn test`, which skips intergation tests
1. run `mvn install` as before again as hope that the error was just a temporary time out.

If there is actually, an integration test failure, then it should be reported so it can be fixed. This will happen if any exchanges change their API in some way.
