### ISSUE TITLE
OKCoin Intl streaming service NPE (3.0.1-SNAPSHOT)

### ISSUE THREAD

**Issue by glabmoris** [timmolter/XChange#862]
The streaming service for OKCoin Intl throws a NPE exception:
```
            (...)
            ExchangeSpecification exSpec = new ExchangeSpecification(exchangeName);
             
            if(exchangeName.equals("com.xeiam.xchange.okcoin.OkCoinExchange")){
               exSpec.setApiKey("XXXXX");
               exSpec.setSecretKey("YYYYY");
               exSpec.setExchangeSpecificParametersItem("Use_Intl", true); 
            }
            
            //Get XChange interface
            Exchange exchange = ExchangeFactory.INSTANCE.createExchange(exSpec); 
            ca.omnibus.Trading.Exchange.Exchange ex = exchanges.bootstrapExchange(exchange);
                       
            final StreamingExchangeService service = exchange.getStreamingExchangeService(new OkCoinExchangeStreamingConfiguration());            

            service.connect();
            
            while(true){
                try {
                  ExchangeEvent event = service.getNextEvent();

                  if(event != null) {
                    System.out.println("---> "  + event.getEventType());

                    if(event.getEventType().equals(ExchangeEventType.TICKER)) {
                      Ticker ticker = (Ticker) event.getPayload();

                      //long x = (new Date()).getTime() - ticker.getTimestamp().getTime();
                      //System.out.println("Delay " + x);
                    }

                  }
                } 
                catch (InterruptedException e) {
                    //interruption handling code here
                }                
            }
```

Stacktraces:

```
Grave:   java.lang.NullPointerException
	at com.xeiam.xchange.okcoin.service.streaming.OkCoinWebSocketService.parseDepth(OkCoinWebSocketService.java:84)
	at com.xeiam.xchange.okcoin.service.streaming.OkCoinWebSocketService.parseMarketData(OkCoinWebSocketService.java:66)
	at com.xeiam.xchange.okcoin.service.streaming.OkCoinWebSocketService.onReceive(OkCoinWebSocketService.java:47)
	at com.xeiam.xchange.okcoin.service.streaming.WebSocketClientHandler.channelRead0(WebSocketClientHandler.java:75)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:971)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:854)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:886)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:834)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

```
Grave:   java.lang.NullPointerException
	at com.xeiam.xchange.okcoin.service.streaming.OkCoinWebSocketService.parseTicker(OkCoinWebSocketService.java:78)
	at com.xeiam.xchange.okcoin.service.streaming.OkCoinWebSocketService.parseMarketData(OkCoinWebSocketService.java:72)
	at com.xeiam.xchange.okcoin.service.streaming.OkCoinWebSocketService.onReceive(OkCoinWebSocketService.java:47)
	at com.xeiam.xchange.okcoin.service.streaming.WebSocketClientHandler.channelRead0(WebSocketClientHandler.java:75)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:971)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:854)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:886)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:834)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

Background: In my app, a thread is started to open a streaming socket to every exchange (that supports it). The aforementioned code is inside the run() method.

**Comment by jheusser** [comment]
@glabmoris Is this resolved now with the fix from yesterday or separate issue?

**Comment by glabmoris** [comment]
Seperate issue completely. This seems related to the parser for WS data. It does receive the data but throws NPEs when parsing it.

**Comment by glabmoris** [comment]
This only happens in the 3.0.1-SNAPSHOT branch. The develop branch's streaming demo runs fine

**Comment by jheusser** [comment]
Ok great, then latest fix seems to fix this (strangely no parsing code has been changed in 3.0.1-SS and develop)

**Comment by glabmoris** [comment]
Can the fact that the consumer and the service reside on the same thread within a JavaEE container be the cause of the issue ?

**Comment by jheusser** [comment]
No unlikely, the switching to international mode did not work in the version before the fix, which then probably tripped up the parsing. If you tested this in develop and it works you can close the issue.

**Comment by glabmoris** [comment]
My app depends on 3.0.1-SNAPSHOT. Maybe changing some dependencies around or updating the snapshot might solve things.

**Comment by glabmoris** [comment]
I forgot to mention that the working demo was for the CNY site. The Intl site doesn't work at all if we tweak the demo to use it:

```
package com.xeiam.xchange.examples.okcoin.streaming;

import java.util.Date;
import java.util.concurrent.TimeUnit;

import com.xeiam.xchange.Exchange;
import com.xeiam.xchange.ExchangeFactory;
import com.xeiam.xchange.ExchangeSpecification;
import com.xeiam.xchange.dto.marketdata.Ticker;
import com.xeiam.xchange.okcoin.OkCoinExchange;
import com.xeiam.xchange.okcoin.service.streaming.OkCoinExchangeStreamingConfiguration;
import com.xeiam.xchange.service.streaming.ExchangeEvent;
import com.xeiam.xchange.service.streaming.ExchangeEventType;
import com.xeiam.xchange.service.streaming.StreamingExchangeService;


public class OkCoinSocketIODemo {

  public static void main(String[] args) throws InterruptedException {

    ExchangeSpecification exSpec = new ExchangeSpecification(OkCoinExchange.class);
    exSpec.setSecretKey("aa");
    exSpec.setApiKey("bb");
    exSpec.setExchangeSpecificParametersItem("Use_Intl", true);     

    Exchange exchange = ExchangeFactory.INSTANCE.createExchange(exSpec);
    final StreamingExchangeService service = exchange.getStreamingExchangeService(new OkCoinExchangeStreamingConfiguration());

    Thread consumer = new Thread("consumer") {

      @Override
      public void run() {

        while (!isInterrupted()) {
          try {
            ExchangeEvent event = service.getNextEvent();

            if(event != null) {
              System.out.println("---> "  + event.getPayload() + " " + event.getEventType());
              
              if(event.getEventType().equals(ExchangeEventType.TICKER)) {
                Ticker ticker = (Ticker) event.getPayload();
                
                long x = (new Date()).getTime() - ticker.getTimestamp().getTime();
                System.out.println("Delay " + x);
              }
              
            }

          } catch (InterruptedException e) {
            this.interrupt();
          }
        }
      }

    };

    // Start consumer.
    consumer.start();

    // Start streaming service.
    service.connect();

    // Demonstrate for 30 seconds.
    TimeUnit.SECONDS.sleep(30);

    // Disconnect streaming service.
    service.disconnect();

    // Interrupt consumer to exit.
    consumer.interrupt();
  }


}

```

**Comment by jheusser** [comment]
are you using develop? Anything but develop will not work with switching to international

**Comment by glabmoris** [comment]
Yes, I'm using develop. I've added Intl demos as use cases if you're interested in documenting both sides more easily (or maybe you'd prefer to have them as unit tests. Your pick)

**Comment by glabmoris** [comment]
Ok, I got the problem: 

```
  public OkCoinExchangeStreamingConfiguration() {
    marketDataCurrencyPairs = new CurrencyPair[]{ CurrencyPair.BTC_CNY };
  }
  
  public OkCoinExchangeStreamingConfiguration(CurrencyPair[] marketDataCurrencyPairs) {
    this.marketDataCurrencyPairs = marketDataCurrencyPairs;
  }  
```

By default, and regardless of the ExchangeSpecification, the CurrencyPair defined for the ExchangeStreamingService is BTC_CNY. In order to get around this, one can pass the currency pair to use. This is ugly, but works:

```
package com.xeiam.xchange.examples.okcoin.streaming;

import java.util.Date;
import java.util.concurrent.TimeUnit;

import com.xeiam.xchange.Exchange;
import com.xeiam.xchange.ExchangeFactory;
import com.xeiam.xchange.ExchangeSpecification;
import com.xeiam.xchange.currency.CurrencyPair;
import com.xeiam.xchange.dto.marketdata.Ticker;
import com.xeiam.xchange.okcoin.OkCoinExchange;
import com.xeiam.xchange.okcoin.service.streaming.OkCoinExchangeStreamingConfiguration;
import com.xeiam.xchange.service.streaming.ExchangeEvent;
import com.xeiam.xchange.service.streaming.ExchangeEventType;
import com.xeiam.xchange.service.streaming.StreamingExchangeService;


public class OkCoinIntlSocketIODemo {

  public static void main(String[] args) throws InterruptedException {

    ExchangeSpecification exSpec = new ExchangeSpecification(OkCoinExchange.class);
    exSpec.setSecretKey("aa");
    exSpec.setApiKey("bb");
    
    //Force intl
    exSpec.setExchangeSpecificParametersItem("Use_Intl", true);     

    Exchange exchange = ExchangeFactory.INSTANCE.createExchange(exSpec);
    
    //Forcing the currency pair is required for Intl
    final StreamingExchangeService service = exchange.getStreamingExchangeService(new OkCoinExchangeStreamingConfiguration(new CurrencyPair[]{ CurrencyPair.BTC_USD }));

    Thread consumer = new Thread("consumer") {

      @Override
      public void run() {

        while (!isInterrupted()) {
          try {
            ExchangeEvent event = service.getNextEvent();

            if(event != null) {
              System.out.println("---> "  + event.getPayload() + " " + event.getEventType());
              
              if(event.getEventType().equals(ExchangeEventType.TICKER)) {
                Ticker ticker = (Ticker) event.getPayload();
                
                long x = (new Date()).getTime() - ticker.getTimestamp().getTime();
                System.out.println("Delay " + x);
              }
              
            }

          } catch (InterruptedException e) {
            this.interrupt();
          }
        }
      }

    };

    // Start consumer.
    consumer.start();

    // Start streaming service.
    service.connect();

    // Demonstrate for 30 seconds.
    TimeUnit.SECONDS.sleep(30);

    // Disconnect streaming service.
    service.disconnect();

    // Interrupt consumer to exit.
    consumer.interrupt();
  }


}

```


I'm submitted the additional unit tests and an appropriate demo in a PR
