### ISSUE TITLE
HttpStatusIOException from BTCEMarketDataService.getOrderBook()

### ISSUE THREAD

**Issue by bryan4887** [timmolter/XChange#873]
This exception surfaces about once per hour for BTCE. 
```
si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 400
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:106)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:137)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:125)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:104)
	at com.sun.proxy.$Proxy12.getDepth(Unknown Source)
	at com.xeiam.xchange.btce.v3.service.polling.BTCEMarketDataServiceRaw.getBTCEDepth(BTCEMarketDataServiceRaw.java:56)
	at com.xeiam.xchange.btce.v3.service.polling.BTCEMarketDataService.getOrderBook(BTCEMarketDataService.java:62)
```

The actual call is:

```
Object[] args = {20};
BTCEMarketDataService.getOrderBook(CurrencyPair.BTC_USD, args);
```
For BTCE, `args[0]` is the depth of the OrderBook that you want.

I am calling this once per 1000ms.  The only thing I can think of is that this exception hits potentially when the book is less than 20 deep?    For BTCE though, I find that *highly* unlikely.

Any suggestions are greatly appreciated.

-Bryan

**Comment by rafalkrupinski** [comment]
Did you try calling it with other argument, say `new int[]{5}`?
Did you enable trace logging for rescu and check the actual HTTP call?
400 is Bad request, so maybe you're right about the order book being too shallow, 
have you tried contacting BTC-e support?

**Comment by rafalkrupinski** [comment]
@bryan4887 Any luck with this?

**Comment by bryan4887** [comment]
Hey @rafalkrupinski I haven't had a chance to follow up on this yet, but I certainly will update everyone when I get a chance.  Thanks again for the suggestions!
