### ISSUE TITLE
okcoin unable to resolve json spec

### ISSUE THREAD

**Issue by douggie** [timmolter/XChange#897]
When trying to load the okcoin exchange it appears it is unable to resolve the correct json file as 

  InputStream is = BaseExchangeService.class.getClassLoader().getResourceAsStream(getMetaDataFileName(exchangeSpecification) + ".json");

in the baseExchange.applySpecification retruns null as it is looking for okcoin_cn_intl.json rahter than OKCoin_intl.json in the resources directory.

issues seems to be the the following code in the okCoinExchange, is that the exchange name is OKCoin_CN rather than okcoin.

  public String getMetaDataFileName(ExchangeSpecification exchangeSpecification) {

    if (exchangeSpecification.getExchangeSpecificParametersItem("Use_Intl").equals(false)) {
      return exchangeSpecification.getExchangeName().toLowerCase().replace(" ", "").replace("-", "").replace(".", "") + "_china";
    } else {
      return exchangeSpecification.getExchangeName().toLowerCase().replace(" ", "").replace("-", "").replace(".", "") + "_intl";

    }
  }

2015-03-21 13:33:33 [main] WARN  com.xeiam.xchange.BaseExchange - An exception occured while loading the metadata file from the classpath. This may lead to unexpected results.
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: UNKNOWN; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164) ~[jackson-databind-2.4.0.jar:2.4.0]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3095) ~[jackson-databind-2.4.0.jar:2.4.0]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3036) ~[jackson-databind-2.4.0.jar:2.4.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2192) ~[jackson-databind-2.4.0.jar:2.4.0]
	at com.xeiam.xchange.BaseExchange.applySpecification(BaseExchange.java:99) ~[xchange-core-3.0.1-SNAPSHOT.jar:na]
	at com.xeiam.xchange.okcoin.OkCoinExchange.applySpecification(OkCoinExchange.java:22) [xchange-okcoin-3.0.1-SNAPSHOT.jar:na]
	at com.xeiam.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:91) [xchange-core-3.0.1-SNAPSHOT.jar:na]

**Comment by jheusser** [comment]
Ah crap,that's with the merge yesterday of the name change. I think we will
have to see if that change makes sense with the new json meta data files or
if we have to revert the change. Will address this later today

**Comment by lazyp** [comment]
I am sorry ,It's me change the exchange name , for differentiate the china stock or international stock or futures exchange

**Comment by douggie** [comment]
Hi lazyP, that sounds like a good plan. I thought may be we have like a 3 in 1 exchange set up for okcoin, like okcoinchina, okcoininter and okcoinfutures, then it would allow arb between all 3.

**Comment by lazyp** [comment]
@jheusser @douggie I'm very sorry , before push PR no test good . I think add more junit test for project , before merge to running all junit test , avoid such event occur again!

**Comment by lazyp** [comment]
Later I make up my fault to fix the bug

**Comment by douggie** [comment]
no worries, i have set the params on the exchange spec directly for it to work. Let me know once the fix is in and I can pull it.

**Comment by douggie** [comment]
we would have nothing without your hard work!

**Comment by lazyp** [comment]
@douggie it has fixed #898

**Comment by douggie** [comment]
Great! Will fetch a bit later today. Thanks so much for a quick turaround.
