### ISSUE TITLE
BitcoinToYou: getOrders: error parsing response when no orders

### ISSUE THREAD

**Issue by mmazi** [timmolter/XChange#922]
Error details:

Can not deserialize instance of com.xeiam.xchange.bitcointoyou.dto.trade.BitcoinToYouOrder[] out of VALUE_STRING token
 at [Source: {  "success": "1",  "oReturn": "NO_RECORD_FOUND"}; line: 1, column: 18]

com.xeiam.xchange.bitcointoyou.service.polling.BitcoinToYouTradeServiceRaw.getBitcoinToYouUserOrders(BitcoinToYouTradeServiceRaw.java:37)
	at com.xeiam.xchange.bitcointoyou.service.polling.BitcoinToYouTradeService.getOpenOrders(BitcoinToYouTradeService.java:36)
	at eu.bitnik.reloaded.repurchase.status.OpenOrderHandler$3.executeAction(OpenOrderHandler.java:150)
	at eu.bitnik.reloaded.repurchase.status.OpenOrderHandler$3.executeAction(OpenOrderHandler.java:147)
	at eu.bitnik.reloaded.exchange.ExchangeAccessor.executeAccess(ExchangeAccessor.java:53)

**Comment by timmolter** [comment]
I removed this module as it was brought to my attention that the API is deprecated.
