### ISSUE TITLE
btcchina FIX API error

### ISSUE THREAD

**Issue by supraniti** [timmolter/XChange#972]
I'm getting this while trying to run btcchina fix client example:

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/mina/common/ByteBufferAllocator
	at com.xeiam.xchange.examples.btcchina.fix.BTCChinaClient.main(BTCChinaClient.java:68)
Caused by: java.lang.ClassNotFoundException: org.apache.mina.common.ByteBufferAllocator
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 1 more

What am I missing?

**Comment by sutra** [comment]
```
<dependency>
	<groupId>org.apache.mina</groupId>
	<artifactId>mina-core</artifactId>
	<version>1.1.7</version>
</dependency>
```

**Comment by Gressill** [comment]
@sutra thx
